// noci/stochastic/pchb.rs
//! Precomputed heat-bath generation of parent-orthogonal BApply connections.
//!
//! Every weight is determinant independent and precomputed once per parent. Doubles use
//! `w_{ij}^{ab}=|\langle ai||jb\rangle|` for same-spin and `w_{ij}^{ab}=|(ai|jb)|` for alpha-beta
//! holes, with hole-pair weights `W_{ij}=\sum_{ab}w_{ij}^{ab}`. Singles use the contracted bound
//! `s_i^a=|h_{ai}|+\sum_j|(ai||jj)|+\sum_{\bar j}|(ai|\bar j\bar j)|` over all orbitals, which
//! bounds `|H_{a\leftarrow i,x}|` for every occupation. From a parent's own reference determinant
//! the singles instead use the exact magnitudes `|H_{a\leftarrow i,0}|`, evaluated once per parent,
//! so vanishing reference singles, as for stationary SCF orbitals, receive vanishing weight
//! without assuming any orbital property.
//!
//! For a source `x` with occupied orbitals `O_x` and virtual orbitals `V_x`, an excitation is
//! generated by first selecting an occupied hole `i` with weight `S_i=\sum_{a\in V_x}s_i^a` or an
//! occupied hole pair with weight `W_{ij}`, both normalised by
//! `Z=\sum_{i\in O_x}S_i+\sum_{ij\in O_x}W_{ij}`, and then particles from `V_x` only. The singles
//! branch probability `p_\text{single}=\sum_i S_i/Z` is therefore chosen automatically, and no
//! draw is rejected for an occupied particle.
//!
//! # References
//! - A. A. Holmes, H. J. Changlani and C. J. Umrigar, *J. Chem. Theory Comput.* **12**,
//!   1561–1571 (2016), [doi:10.1021/acs.jctc.5b01170](https://doi.org/10.1021/acs.jctc.5b01170),
//!   for precomputed heat-bath double excitations.
//! - O. Weser, A. Alavi and G. Li Manni, *J. Chem. Theory Comput.* **19**, 9118 (2023),
//!   [doi:10.1021/acs.jctc.3c00546](https://doi.org/10.1021/acs.jctc.3c00546), for contracted
//!   single-excitation weights and particle selection restricted to empty orbitals.

// External crate imports.
use ndarray::{Array2, Array4};
use rand::Rng;

// Crate-root imports.
use crate::determinant::{NOCIIndex, OrthogonalConnection};
use crate::elements::{
    MOCache, NOCIData, OrthogonalHamiltonianScratch, calculate_h_pairs_orthogonal_batched,
};

/// Enumerate unordered orbital pairs `(p,q)`, `p<q`, in compact-label order.
/// The label of `(p,q)` is `p(2n-p-1)/2 + q-p-1`.
/// # Arguments:
/// - `n`: Number of orbitals.
/// # Returns:
/// - `Vec<(u8, u8)>`: Ordered orbital pairs.
fn orbital_pairs(n: usize) -> Vec<(u8, u8)> {
    let mut pairs = Vec::with_capacity(n * n.saturating_sub(1) / 2);
    for p in 0..n {
        for q in p + 1..n {
            pairs.push((p as u8, q as u8));
        }
    }
    pairs
}

/// Return the compact label of an unordered orbital pair `(p,q)`, `p<q`.
/// # Arguments:
/// - `p`: Smaller orbital label.
/// - `q`: Larger orbital label.
/// - `n`: Number of orbitals.
/// # Returns:
/// - `usize`: Label `p(2n-p-1)/2 + q-p-1`.
#[inline(always)]
fn pair_label(
    p: usize,
    q: usize,
    n: usize,
) -> usize {
    p * (2 * n - p - 1) / 2 + q - p - 1
}

/// Precompute contracted single-excitation weights for one spin.
/// `s_i^a=|h_{ai}|+\sum_j|(ai||jj)|+\sum_{\bar j}|(ai|\bar j\bar j)|` sums every orbital `j` of
/// the same spin and every orbital `\bar j` of the other spin, so `s_i^a \ge |H_{a\leftarrow i,x}|`
/// for any occupation.
/// # Arguments:
/// - `h`: One-electron Hamiltonian in this spin's MO basis.
/// - `same`: Antisymmetrised same-spin ERIs `(pq||rs)` in this spin's MO basis.
/// - `other`: Opposite-spin Coulomb coupling `(ai|\bar j\bar j)` as a function of `(a,i,\bar j)`.
/// - `nother`: Number of opposite-spin orbitals.
/// # Returns:
/// - `Vec<f64>`: Weights `s_i^a`, indexed `i n + a`, zero on the diagonal `a=i`.
fn single_weights<F: Fn(usize, usize, usize) -> f64>(
    h: &Array2<f64>,
    same: &Array4<f64>,
    other: F,
    nother: usize,
) -> Vec<f64> {
    let n = h.nrows();
    let mut weights = vec![0.0; n * n];
    for i in 0..n {
        for a in 0..n {
            if a == i {
                continue;
            }
            let mut w = h[(a, i)].abs();
            for j in 0..n {
                w += same[(a, i, j, j)].abs();
            }
            for j in 0..nother {
                w += other(a, i, j).abs();
            }
            weights[i * n + a] = w;
        }
    }
    weights
}

/// Precomputed excitation weights in one parent's orthonormal MO basis.
struct PchbParent {
    /// Number of alpha orbitals.
    na: usize,
    /// Number of beta orbitals.
    nb: usize,
    /// Alpha single weights `s_i^a`, indexed `i n_\alpha + a`.
    single_a: Vec<f64>,
    /// Beta single weights `s_i^a`, indexed `i n_\beta + a`.
    single_b: Vec<f64>,
    /// Exact alpha reference singles `|H_{a\leftarrow i,0}|`, indexed `i n_\alpha + a`, or empty
    /// when the parent reference is not retained.
    exact_a: Vec<f64>,
    /// Exact beta reference singles `|H_{a\leftarrow i,0}|`, indexed `i n_\beta + a`, or empty
    /// when the parent reference is not retained.
    exact_b: Vec<f64>,
    /// Alpha-alpha hole-pair weights `W_{ij}=\sum_{a<b}|\langle ai||jb\rangle|`.
    weight_aa: Vec<f64>,
    /// Beta-beta hole-pair weights `W_{ij}=\sum_{a<b}|\langle ai||jb\rangle|`.
    weight_bb: Vec<f64>,
    /// Alpha-beta hole-pair weights `W_{ij}=\sum_{ab}|(ai|jb)|`, indexed `i n_\beta + j`.
    weight_ab: Vec<f64>,
    /// Alpha-alpha particle weights `w_{ij}^{ab}`, indexed `[ij, ab]` by compact pair labels.
    rows_aa: Vec<f64>,
    /// Beta-beta particle weights `w_{ij}^{ab}`, indexed `[ij, ab]` by compact pair labels.
    rows_bb: Vec<f64>,
    /// Alpha-beta particle weights `w_{ij}^{ab}`, indexed `[i n_\beta + j, a n_\beta + b]`.
    rows_ab: Vec<f64>,
}

impl PchbParent {
    /// Precompute single, hole-pair and particle-pair weights from one parent's integrals.
    /// Same-spin doubles use `|H_{ab\leftarrow ij}|=|\langle ai||jb\rangle|` and alpha-beta
    /// doubles `|(ai|jb)|`, both independent of the remaining occupation. Particle pairs that
    /// reuse a hole orbital receive zero weight.
    /// # Arguments:
    /// - `cache`: Parent MO integrals with antisymmetrised same-spin and Coulomb alpha-beta ERIs.
    /// # Returns:
    /// - `Self`: Parent-local PCHB weights.
    fn new(cache: &MOCache<f64>) -> Self {
        let na = cache.ha.nrows();
        let nb = cache.hb.nrows();

        // Contracted singles bound for each spin; the alpha-beta tensor is `(\alpha\alpha|\beta\beta)`.
        let single_a = single_weights(
            &cache.ha,
            &cache.eri_aa_asym,
            |a, i, j| cache.eri_ab_coul[(a, i, j, j)],
            nb,
        );
        let single_b = single_weights(
            &cache.hb,
            &cache.eri_bb_asym,
            |a, i, j| cache.eri_ab_coul[(j, j, i, a)],
            na,
        );

        // Same-spin rows over hole pairs `i<j` and particle pairs `a<b`.
        let same = |n: usize, eri: &Array4<f64>| {
            let pairs = orbital_pairs(n);
            let mut weights = Vec::with_capacity(pairs.len());
            let mut rows = Vec::with_capacity(pairs.len() * pairs.len());
            for &(i, j) in &pairs {
                let start = rows.len();
                for &(a, b) in &pairs {
                    rows.push(if a == i || a == j || b == i || b == j {
                        0.0
                    } else {
                        eri[(a as usize, i as usize, j as usize, b as usize)].abs()
                    });
                }
                weights.push(rows[start..].iter().sum::<f64>());
            }
            (weights, rows)
        };
        let (weight_aa, rows_aa) = same(na, &cache.eri_aa_asym);
        let (weight_bb, rows_bb) = same(nb, &cache.eri_bb_asym);

        // Alpha-beta rows over holes `(i_\alpha, j_\beta)` and particles `(a_\alpha, b_\beta)`.
        let mut weight_ab = Vec::with_capacity(na * nb);
        let mut rows_ab = Vec::with_capacity(na * nb * na * nb);
        for i in 0..na {
            for j in 0..nb {
                let start = rows_ab.len();
                for a in 0..na {
                    for b in 0..nb {
                        rows_ab.push(if a == i || b == j {
                            0.0
                        } else {
                            cache.eri_ab_coul[(a, i, j, b)].abs()
                        });
                    }
                }
                weight_ab.push(rows_ab[start..].iter().sum::<f64>());
            }
        }

        Self {
            na,
            nb,
            single_a,
            single_b,
            exact_a: Vec::new(),
            exact_b: Vec::new(),
            weight_aa,
            weight_bb,
            weight_ab,
            rows_aa,
            rows_bb,
            rows_ab,
        }
    }

    /// Return the heap storage of this parent's weights.
    /// # Arguments:
    /// - `self`: Parent-local PCHB weights.
    /// # Returns:
    /// - `usize`: Bytes held by single, hole-pair and particle-pair weights.
    fn bytes(&self) -> usize {
        (self.single_a.len()
            + self.single_b.len()
            + self.exact_a.len()
            + self.exact_b.len()
            + self.weight_aa.len()
            + self.weight_bb.len()
            + self.weight_ab.len()
            + self.rows_aa.len()
            + self.rows_bb.len()
            + self.rows_ab.len())
            * size_of::<f64>()
    }

    /// Evaluate the exact reference singles `|H_{a\leftarrow i,0}|` for every occupied `i` and
    /// virtual `a` of the parent reference with the orthogonal Slater-Condon kernel.
    /// # Arguments:
    /// - `self`: Parent-local PCHB weights to extend.
    /// - `data`: NOCI data holding the determinant space and parent MO caches.
    /// - `reference`: Retained index of this parent's reference determinant.
    /// - `scratch`: Reusable orthogonal Hamiltonian grouping storage.
    /// # Returns:
    /// - `()`: Fills `exact_a` and `exact_b`.
    fn reference_singles(
        &mut self,
        data: &NOCIData<'_, f64>,
        reference: NOCIIndex,
        scratch: &mut OrthogonalHamiltonianScratch,
    ) {
        // Enumerate every reference single in source-rank form with its orbital labels.
        let alpha = data.space.alpha(reference);
        let beta = data.space.beta(reference);
        let mut labels = Vec::new();
        let mut pairs = Vec::new();
        for (x, &i) in alpha.occupied.iter().enumerate() {
            for (y, &a) in alpha.virtuals.iter().enumerate() {
                labels.push((true, i as usize, a as usize));
                pairs.push((
                    reference,
                    OrthogonalConnection::AlphaSingle {
                        occupied: x as u8,
                        virtual_: y as u8,
                    },
                ));
            }
        }
        for (x, &i) in beta.occupied.iter().enumerate() {
            for (y, &a) in beta.virtuals.iter().enumerate() {
                labels.push((false, i as usize, a as usize));
                pairs.push((
                    reference,
                    OrthogonalConnection::BetaSingle {
                        occupied: x as u8,
                        virtual_: y as u8,
                    },
                ));
            }
        }

        // Evaluate `H_{a\leftarrow i,0}` once and store magnitudes by orbital label.
        let mut values = vec![0.0; pairs.len()];
        calculate_h_pairs_orthogonal_batched(data, &pairs, scratch, &mut values);
        self.exact_a = vec![0.0; self.na * self.na];
        self.exact_b = vec![0.0; self.nb * self.nb];
        for (&(spin, i, a), value) in labels.iter().zip(values) {
            if spin {
                self.exact_a[i * self.na + a] = value.abs();
            } else {
                self.exact_b[i * self.nb + a] = value.abs();
            }
        }
    }

    /// Return the single-excitation weights for one source.
    /// # Arguments:
    /// - `self`: Parent-local PCHB weights.
    /// - `reference`: Whether the source is this parent's reference determinant.
    /// # Returns:
    /// - `(&[f64], &[f64])`: Alpha and beta weights, exact `|H_{a\leftarrow i,0}|` for the
    ///   reference and the contracted bound `s_i^a` otherwise.
    fn singles(
        &self,
        reference: bool,
    ) -> (&[f64], &[f64]) {
        if reference {
            (&self.exact_a, &self.exact_b)
        } else {
            (&self.single_a, &self.single_b)
        }
    }
}

/// Hole selection of the prepared source.
#[derive(Clone, Copy)]
enum Hole {
    /// One alpha hole `i` for a single excitation.
    AlphaSingle(u8),
    /// One beta hole `i` for a single excitation.
    BetaSingle(u8),
    /// Two alpha holes `(i,j)`, `i<j`, with their compact pair label.
    AlphaDouble(u8, u8, u32),
    /// Two beta holes `(i,j)`, `i<j`, with their compact pair label.
    BetaDouble(u8, u8, u32),
    /// One alpha hole `i` and one beta hole `j` with their label `i n_\beta + j`.
    MixedDouble(u8, u8, u32),
}

/// Per-source sampling state built once before all attempts from one source.
pub(in crate::noci::stochastic) struct PchbScratch {
    /// Parent orbital frame of the prepared source.
    parent: usize,
    /// Whether the prepared source is its parent's reference with exact single weights.
    reference: bool,
    /// Virtual alpha orbital labels of the source in ascending order.
    virtuals_a: Vec<u8>,
    /// Virtual beta orbital labels of the source in ascending order.
    virtuals_b: Vec<u8>,
    /// Occupied or virtual rank of each alpha orbital label in the source.
    rank_a: Vec<u8>,
    /// Occupied or virtual rank of each beta orbital label in the source.
    rank_b: Vec<u8>,
    /// Occupied holes and hole pairs with nonzero weight and the weight itself.
    holes: Vec<(Hole, f64)>,
    /// Cumulative hole weights aligned with `holes`, ending at `Z`.
    holes_cdf: Vec<f64>,
}

impl PchbScratch {
    /// Construct empty per-source PCHB storage.
    /// # Returns:
    /// - `Self`: Empty scratch reused across sources.
    pub(in crate::noci::stochastic) fn new() -> Self {
        Self {
            parent: 0,
            reference: false,
            virtuals_a: Vec::new(),
            virtuals_b: Vec::new(),
            rank_a: Vec::new(),
            rank_b: Vec::new(),
            holes: Vec::new(),
            holes_cdf: Vec::new(),
        }
    }
}

/// Draw one particle from the source's virtual orbitals with probability
/// `s_i^a/\sum_{c\in V_x}s_i^c`.
/// # Arguments:
/// - `virtuals`: Candidate particle labels.
/// - `weight`: Particle weight lookup `s_i^a`.
/// - `rng`: Thread-local random-number generator.
/// # Returns:
/// - `Option<(u8, f64)>`: Particle `a` and its conditional probability, or `None` when every
///   virtual orbital has zero weight.
fn sample_particle<R: Rng + ?Sized, F: Fn(u8) -> f64>(
    virtuals: &[u8],
    weight: F,
    rng: &mut R,
) -> Option<(u8, f64)> {
    // Normalise over the source's virtual orbitals, then invert the cumulative distribution.
    let valid = virtuals.iter().map(|&a| weight(a)).sum::<f64>();
    if valid <= 0.0 {
        return None;
    }
    let target = rng.r#gen::<f64>() * valid;
    let mut cumulative = 0.0;
    for &a in virtuals {
        let w = weight(a);
        cumulative += w;
        if w > 0.0 && cumulative > target {
            return Some((a, w / valid));
        }
    }
    None
}

/// Draw one particle pair from the source's virtual orbitals with probability
/// `w_{ij}^{ab}/\sum_{cd\in V_x}w_{ij}^{cd}`.
/// # Arguments:
/// - `virtuals`: Candidate particle labels, ascending for same-spin pairs.
/// - `second`: Beta candidate labels for alpha-beta pairs, or `None` for same-spin pairs.
/// - `weight`: Particle weight lookup `w_{ij}^{ab}` for a candidate `(a,b)`.
/// - `rng`: Thread-local random-number generator.
/// # Returns:
/// - `Option<(u8, u8, f64)>`: Particles `(a,b)` and their conditional probability, or `None`
///   when every valid particle pair has zero weight.
fn sample_particles<R: Rng + ?Sized, F: Fn(u8, u8) -> f64>(
    virtuals: &[u8],
    second: Option<&[u8]>,
    weight: F,
    rng: &mut R,
) -> Option<(u8, u8, f64)> {
    // Visit every valid `(a,b)`: `a<b` in one spin, or the Cartesian alpha-beta product.
    let visit = |f: &mut dyn FnMut(u8, u8) -> bool| match second {
        None => {
            for (x, &a) in virtuals.iter().enumerate() {
                for &b in &virtuals[x + 1..] {
                    if f(a, b) {
                        return;
                    }
                }
            }
        }
        Some(beta) => {
            for &a in virtuals {
                for &b in beta {
                    if f(a, b) {
                        return;
                    }
                }
            }
        }
    };

    // Normalise over the valid particle pairs of this source.
    let mut valid = 0.0;
    visit(&mut |a, b| {
        valid += weight(a, b);
        false
    });
    if valid <= 0.0 {
        return None;
    }

    // Invert the cumulative distribution of the valid pairs.
    let target = rng.r#gen::<f64>() * valid;
    let mut cumulative = 0.0;
    let mut chosen = None;
    visit(&mut |a, b| {
        let w = weight(a, b);
        cumulative += w;
        if w > 0.0 && cumulative > target {
            chosen = Some((a, b, w / valid));
            true
        } else {
            false
        }
    });
    chosen
}

/// Precomputed heat-bath generator over every parent's orthogonal connections.
pub(in crate::noci::stochastic) struct PchbGenerator {
    /// Parent-local excitation weights.
    parents: Vec<PchbParent>,
}

impl PchbGenerator {
    /// Precompute excitation weights for every parent, including exact singles from each
    /// retained parent reference.
    /// # Arguments:
    /// - `data`: NOCI data holding the determinant space and parent MO caches.
    /// - `mocache`: Parent MO integral caches, one per parent reference.
    /// # Returns:
    /// - `Self`: PCHB generator shared read-only by every worker.
    pub(in crate::noci::stochastic) fn new(
        data: &NOCIData<'_, f64>,
        mocache: &[MOCache<f64>],
    ) -> Self {
        let mut parents: Vec<PchbParent> = mocache.iter().map(PchbParent::new).collect();

        // A parent reference is the retained determinant without parent-relative holes.
        let mut scratch = OrthogonalHamiltonianScratch::new(parents.len());
        for index in (0..data.space.len()).map(NOCIIndex) {
            let parent = data.space.state(index).parent;
            let (alpha, beta) = data.space.excitations(index);
            if alpha.holes == 0 && beta.holes == 0 && parent < parents.len() {
                parents[parent].reference_singles(data, index, &mut scratch);
            }
        }

        Self { parents }
    }

    /// Return the heap storage of all precomputed weights.
    /// # Arguments:
    /// - `self`: PCHB generator.
    /// # Returns:
    /// - `usize`: Total bytes held by parent weights.
    pub(in crate::noci::stochastic) fn bytes(&self) -> usize {
        self.parents.iter().map(PchbParent::bytes).sum()
    }

    /// Build the source-dependent hole distribution
    /// `P(i)=S_i/Z`, `P(ij)=W_{ij}/Z` with `S_i=\sum_{a\in V_x}s_i^a`, where a parent reference
    /// source replaces `s_i^a` by the exact `|H_{a\leftarrow i,0}|`.
    /// # Arguments:
    /// - `self`: PCHB generator.
    /// - `source`: Retained source determinant `x`.
    /// - `data`: NOCI data holding the determinant space.
    /// - `scratch`: Per-source sampling state to overwrite.
    /// # Returns:
    /// - `()`: Fills `scratch` for all attempts from `source`.
    pub(in crate::noci::stochastic) fn prepare(
        &self,
        source: NOCIIndex,
        data: &NOCIData<'_, f64>,
        scratch: &mut PchbScratch,
    ) {
        let parent = data.space.state(source).parent;
        let tables = &self.parents[parent];
        let alpha = data.space.alpha(source);
        let beta = data.space.beta(source);
        scratch.parent = parent;
        scratch.reference = alpha.excitation.holes == 0
            && beta.excitation.holes == 0
            && !tables.exact_a.is_empty();
        let (single_a, single_b) = tables.singles(scratch.reference);
        scratch.virtuals_a.clone_from(&alpha.virtuals);
        scratch.virtuals_b.clone_from(&beta.virtuals);

        // Map orbital labels to the occupied/virtual ranks used by `OrthogonalConnection`.
        scratch.rank_a.clear();
        scratch.rank_a.resize(tables.na, 0);
        for (rank, &orbital) in alpha.occupied.iter().enumerate() {
            scratch.rank_a[orbital as usize] = rank as u8;
        }
        for (rank, &orbital) in alpha.virtuals.iter().enumerate() {
            scratch.rank_a[orbital as usize] = rank as u8;
        }
        scratch.rank_b.clear();
        scratch.rank_b.resize(tables.nb, 0);
        for (rank, &orbital) in beta.occupied.iter().enumerate() {
            scratch.rank_b[orbital as usize] = rank as u8;
        }
        for (rank, &orbital) in beta.virtuals.iter().enumerate() {
            scratch.rank_b[orbital as usize] = rank as u8;
        }

        // One cumulative distribution over single holes followed by hole pairs, so one uniform
        // draw selects the class and the holes with `p_\text{single}` chosen automatically.
        scratch.holes.clear();
        scratch.holes_cdf.clear();
        let mut total = 0.0;
        let mut push = |hole: Hole, weight: f64| {
            if weight > 0.0 {
                total += weight;
                scratch.holes.push((hole, weight));
                scratch.holes_cdf.push(total);
            }
        };

        // Single holes carry `S_i=\sum_{a\in V_x}s_i^a` restricted to the source's virtuals.
        for &i in &alpha.occupied {
            let row = &single_a[i as usize * tables.na..(i as usize + 1) * tables.na];
            let weight = alpha.virtuals.iter().map(|&a| row[a as usize]).sum();
            push(Hole::AlphaSingle(i), weight);
        }
        for &i in &beta.occupied {
            let row = &single_b[i as usize * tables.nb..(i as usize + 1) * tables.nb];
            let weight = beta.virtuals.iter().map(|&a| row[a as usize]).sum();
            push(Hole::BetaSingle(i), weight);
        }

        // Occupied hole pairs in all three spin channels carry the precomputed `W_{ij}`.
        for (x, &i) in alpha.occupied.iter().enumerate() {
            for &j in &alpha.occupied[x + 1..] {
                let label = pair_label(i as usize, j as usize, tables.na);
                push(
                    Hole::AlphaDouble(i, j, label as u32),
                    tables.weight_aa[label],
                );
            }
        }
        for (x, &i) in beta.occupied.iter().enumerate() {
            for &j in &beta.occupied[x + 1..] {
                let label = pair_label(i as usize, j as usize, tables.nb);
                push(
                    Hole::BetaDouble(i, j, label as u32),
                    tables.weight_bb[label],
                );
            }
        }
        for &i in &alpha.occupied {
            for &j in &beta.occupied {
                let label = i as usize * tables.nb + j as usize;
                push(
                    Hole::MixedDouble(i, j, label as u32),
                    tables.weight_ab[label],
                );
            }
        }
    }

    /// Sample one connection of the prepared source with its exact generation probability.
    /// Singles have `P_\text{gen}=(S_i/Z)\,s_i^a/S_i` and doubles
    /// `P_\text{gen}=(W_{ij}/Z)\,w_{ij}^{ab}/\sum_{cd\in V_x}w_{ij}^{cd}`.
    /// # Arguments:
    /// - `self`: PCHB generator.
    /// - `scratch`: Source distributions from `prepare`.
    /// - `rng`: Thread-local random-number generator.
    /// # Returns:
    /// - `Option<(OrthogonalConnection, f64)>`: Source-relative connection and `P_\text{gen}`, or
    ///   `None` when the source has no weight or the chosen holes have no valid particles.
    pub(in crate::noci::stochastic) fn sample<R: Rng + ?Sized>(
        &self,
        scratch: &PchbScratch,
        rng: &mut R,
    ) -> Option<(OrthogonalConnection, f64)> {
        // Select holes with probability `S_i/Z` or `W_{ij}/Z`.
        let total = *scratch.holes_cdf.last()?;
        let u = rng.r#gen::<f64>() * total;
        let k = scratch
            .holes_cdf
            .partition_point(|&c| c <= u)
            .min(scratch.holes.len() - 1);
        let (hole, weight) = scratch.holes[k];
        let p = weight / total;
        let tables = &self.parents[scratch.parent];
        let (single_a, single_b) = tables.singles(scratch.reference);
        let (ra, rb) = (&scratch.rank_a, &scratch.rank_b);

        // Draw particles from the source's virtual orbitals and map labels to source ranks.
        match hole {
            Hole::AlphaSingle(i) => {
                let row = &single_a[i as usize * tables.na..(i as usize + 1) * tables.na];
                let (a, q) = sample_particle(&scratch.virtuals_a, |a| row[a as usize], rng)?;
                Some((
                    OrthogonalConnection::AlphaSingle {
                        occupied: ra[i as usize],
                        virtual_: ra[a as usize],
                    },
                    p * q,
                ))
            }
            Hole::BetaSingle(i) => {
                let row = &single_b[i as usize * tables.nb..(i as usize + 1) * tables.nb];
                let (a, q) = sample_particle(&scratch.virtuals_b, |a| row[a as usize], rng)?;
                Some((
                    OrthogonalConnection::BetaSingle {
                        occupied: rb[i as usize],
                        virtual_: rb[a as usize],
                    },
                    p * q,
                ))
            }
            Hole::AlphaDouble(i, j, label) => {
                let width = tables.na * (tables.na - 1) / 2;
                let label = label as usize;
                let row = &tables.rows_aa[label * width..(label + 1) * width];
                let (a, b, q) = sample_particles(
                    &scratch.virtuals_a,
                    None,
                    |a, b| row[pair_label(a as usize, b as usize, tables.na)],
                    rng,
                )?;
                Some((
                    OrthogonalConnection::AlphaDouble {
                        occupied: [ra[i as usize], ra[j as usize]],
                        virtual_: [ra[a as usize], ra[b as usize]],
                    },
                    p * q,
                ))
            }
            Hole::BetaDouble(i, j, label) => {
                let width = tables.nb * (tables.nb - 1) / 2;
                let label = label as usize;
                let row = &tables.rows_bb[label * width..(label + 1) * width];
                let (a, b, q) = sample_particles(
                    &scratch.virtuals_b,
                    None,
                    |a, b| row[pair_label(a as usize, b as usize, tables.nb)],
                    rng,
                )?;
                Some((
                    OrthogonalConnection::BetaDouble {
                        occupied: [rb[i as usize], rb[j as usize]],
                        virtual_: [rb[a as usize], rb[b as usize]],
                    },
                    p * q,
                ))
            }
            Hole::MixedDouble(i, j, label) => {
                let width = tables.na * tables.nb;
                let label = label as usize;
                let row = &tables.rows_ab[label * width..(label + 1) * width];
                let (a, b, q) = sample_particles(
                    &scratch.virtuals_a,
                    Some(&scratch.virtuals_b),
                    |a, b| row[a as usize * tables.nb + b as usize],
                    rng,
                )?;
                Some((
                    OrthogonalConnection::AlphaBetaDouble {
                        occupied_a: ra[i as usize],
                        virtual_a: ra[a as usize],
                        occupied_b: rb[j as usize],
                        virtual_b: rb[b as usize],
                    },
                    p * q,
                ))
            }
        }
    }
}
