// deterministic/noccmc/overlap.rs
// This file is generated by tools/wick/rust.py.
// Do not edit generated overlap kernels by hand.

use crate::deterministic::noccmc::space::{Excitation, ExcitationClass, Spaces, excitation_class};
use crate::noci::{Cumulants, RDM1};

/// Unpack one single excitation.
/// # Arguments:
/// - `ex`: Excitation expected to be a single excitation.
/// # Returns:
/// - `(usize, usize)`: Creation and annihilation orbital indices.
fn single(ex: Excitation) -> (usize, usize) {
    match ex {
        Excitation::Single { p, q } => (p, q),
        _ => panic!("expected single excitation"),
    }
}

/// Unpack one double excitation.
/// # Arguments:
/// - `ex`: Excitation expected to be a double excitation.
/// # Returns:
/// - `(usize, usize, usize, usize)`: Two creation and two annihilation orbital indices.
fn double(ex: Excitation) -> (usize, usize, usize, usize) {
    match ex {
        Excitation::Double { p, q, r, s } => (p, q, r, s),
        _ => panic!("expected double excitation"),
    }
}

/// Evaluate a Kronecker delta.
/// # Arguments:
/// - `p`: Left orbital index.
/// - `q`: Right orbital index.
/// # Returns:
/// - `f64`: `1.0` if the indices are equal, otherwise `0.0`.
fn delta(
    p: usize,
    q: usize,
) -> f64 {
    if p == q { 1.0 } else { 0.0 }
}

/// Evaluate an active-space hole density.
/// # Arguments:
/// - `gamma1`: Spin-free one-particle RDM.
/// - `p`: Upper orbital index.
/// - `q`: Lower orbital index.
/// # Returns:
/// - `f64`: `Theta^p_q = 2 delta^p_q - Gamma^p_q`.
fn theta(
    gamma1: &RDM1<f64>,
    p: usize,
    q: usize,
) -> f64 {
    2.0 * delta(p, q) - gamma1.data[p * gamma1.n + q]
}

/// Convert a global orbital index to an active-space index.
/// # Arguments:
/// - `spaces`: Orbital-space partitioning and index maps.
/// - `p`: Global orbital index.
/// # Returns:
/// - `usize`: Active-space index corresponding to `p`.
fn active(
    spaces: &Spaces,
    p: usize,
) -> usize {
    spaces.active_map[p].expect("expected active orbital index")
}

/// Evaluate one generated FOIS overlap metric element.
/// # Arguments:
/// - `left`: Left excitation operator.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element, or `0.0` for orthogonal class pairs.
pub(crate) fn overlap_element(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let lclass = excitation_class(spaces, left);
    let rclass = excitation_class(spaces, right);

    match (lclass, rclass) {
        (ExcitationClass::CToA, ExcitationClass::CToA) => {
            overlap_c_to_a_c_to_a(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AToV, ExcitationClass::AToV) => {
            overlap_a_to_v_a_to_v(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AToA, ExcitationClass::AToA) => {
            overlap_a_to_a_a_to_a(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToAV, ExcitationClass::CAToAV) => {
            overlap_ca_to_av_ca_to_av(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToVA, ExcitationClass::CAToVA) => {
            overlap_ca_to_va_ca_to_va(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToVV, ExcitationClass::CAToVV) => {
            overlap_ca_to_vv_ca_to_vv(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CCToAV, ExcitationClass::CCToAV) => {
            overlap_cc_to_av_cc_to_av(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CCToAA, ExcitationClass::CCToAA) => {
            overlap_cc_to_aa_cc_to_aa(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToAA, ExcitationClass::CAToAA) => {
            overlap_ca_to_aa_ca_to_aa(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AAToAV, ExcitationClass::AAToAV) => {
            overlap_aa_to_av_aa_to_av(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AAToVV, ExcitationClass::AAToVV) => {
            overlap_aa_to_vv_aa_to_vv(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AAToAA, ExcitationClass::AAToAA) => {
            overlap_aa_to_aa_aa_to_aa(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AToV, ExcitationClass::AAToAV) => {
            overlap_a_to_v_aa_to_av(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AAToAV, ExcitationClass::AToV) => {
            overlap_a_to_v_aa_to_av(right, left, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CToA, ExcitationClass::CAToAA) => {
            overlap_c_to_a_ca_to_aa(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToAA, ExcitationClass::CToA) => {
            overlap_c_to_a_ca_to_aa(right, left, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AToA, ExcitationClass::AAToAA) => {
            overlap_a_to_a_aa_to_aa(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::AAToAA, ExcitationClass::AToA) => {
            overlap_a_to_a_aa_to_aa(right, left, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToAV, ExcitationClass::CAToVA) => {
            overlap_ca_to_av_ca_to_va(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToVA, ExcitationClass::CAToAV) => {
            overlap_ca_to_av_ca_to_va(right, left, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CToV, ExcitationClass::CToV) => {
            overlap_c_to_v_c_to_v(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CToV, ExcitationClass::CAToAV) => {
            overlap_c_to_v_ca_to_av(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToAV, ExcitationClass::CToV) => {
            overlap_c_to_v_ca_to_av(right, left, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CToV, ExcitationClass::CAToVA) => {
            overlap_c_to_v_ca_to_va(left, right, spaces, gamma1, lambdas)
        }
        (ExcitationClass::CAToVA, ExcitationClass::CToV) => {
            overlap_c_to_v_ca_to_va(right, left, spaces, gamma1, lambdas)
        }
        _ => 0.0,
    }
}

/// Evaluate generated Appendix-C overlap block `C1`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_c_to_a_c_to_a(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (u, i) = single(left);
    let (v, j) = single(right);
    let mut out = 0.0;
    out += delta(i, j) * theta(gamma1, v, u);
    out
}

/// Evaluate generated Appendix-C overlap block `C2`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_a_to_v_a_to_v(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, t) = single(left);
    let (b, u) = single(right);
    let mut out = 0.0;
    out += delta(a, b) * gamma1.data[t * gamma1.n + u];
    out
}

/// Evaluate generated Appendix-C overlap block `C3`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_a_to_a_a_to_a(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (v, u) = single(left);
    let (x, w) = single(right);
    let mut out = 0.0;
    out += (1.0 / 2.0) * gamma1.data[u * gamma1.n + w] * theta(gamma1, x, v);
    out += lambdas.lambda2.get(
        &[active(spaces, u), active(spaces, x)],
        &[active(spaces, v), active(spaces, w)],
    );
    out
}

/// Evaluate generated Appendix-C overlap block `C4`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_ca_to_av_ca_to_av(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (v, a, i, u) = double(left);
    let (x, b, j, w) = double(right);
    let mut out = 0.0;
    out += delta(a, b) * delta(i, j) * gamma1.data[u * gamma1.n + w] * theta(gamma1, x, v);
    out += -1.0
        * delta(a, b)
        * delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, x)],
            &[active(spaces, w), active(spaces, v)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C5`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_ca_to_va_ca_to_va(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, v, i, u) = double(left);
    let (b, x, j, w) = double(right);
    let mut out = 0.0;
    out += delta(a, b) * delta(i, j) * gamma1.data[u * gamma1.n + w] * theta(gamma1, x, v);
    out += 2.0
        * delta(a, b)
        * delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, x)],
            &[active(spaces, v), active(spaces, w)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C6`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_ca_to_vv_ca_to_vv(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, b, i, u) = double(left);
    let (c, d, j, v) = double(right);
    let mut out = 0.0;
    out += 2.0 * delta(a, c) * delta(b, d) * delta(i, j) * gamma1.data[u * gamma1.n + v];
    out += -1.0 * delta(a, d) * delta(b, c) * delta(i, j) * gamma1.data[u * gamma1.n + v];
    out
}

/// Evaluate generated Appendix-C overlap block `C7`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_cc_to_av_cc_to_av(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (u, a, i, j) = double(left);
    let (v, b, k, l) = double(right);
    let mut out = 0.0;
    out += 2.0 * delta(a, b) * delta(i, k) * delta(j, l) * theta(gamma1, v, u);
    out += -1.0 * delta(a, b) * delta(i, l) * delta(j, k) * theta(gamma1, v, u);
    out
}

/// Evaluate generated Appendix-C overlap block `C8`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_cc_to_aa_cc_to_aa(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (u, v, i, j) = double(left);
    let (w, x, k, l) = double(right);
    let mut out = 0.0;
    out += delta(i, k)
        * delta(j, l)
        * lambdas.lambda2.get(
            &[active(spaces, w), active(spaces, x)],
            &[active(spaces, u), active(spaces, v)],
        );
    out += delta(i, k) * delta(j, l) * theta(gamma1, w, u) * theta(gamma1, x, v);
    out += (-1.0 / 2.0) * delta(i, k) * delta(j, l) * theta(gamma1, w, v) * theta(gamma1, x, u);
    out += delta(i, l)
        * delta(j, k)
        * lambdas.lambda2.get(
            &[active(spaces, w), active(spaces, x)],
            &[active(spaces, v), active(spaces, u)],
        );
    out += (-1.0 / 2.0) * delta(i, l) * delta(j, k) * theta(gamma1, w, u) * theta(gamma1, x, v);
    out += delta(i, l) * delta(j, k) * theta(gamma1, w, v) * theta(gamma1, x, u);
    out
}

/// Evaluate generated Appendix-C overlap block `C9`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_ca_to_aa_ca_to_aa(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (v, w, i, u) = double(left);
    let (y, z, j, x) = double(right);
    let mut out = 0.0;
    out += (1.0 / 2.0)
        * delta(i, j)
        * gamma1.data[u * gamma1.n + x]
        * lambdas.lambda2.get(
            &[active(spaces, y), active(spaces, z)],
            &[active(spaces, v), active(spaces, w)],
        );
    out += (1.0 / 2.0)
        * delta(i, j)
        * gamma1.data[u * gamma1.n + x]
        * theta(gamma1, y, v)
        * theta(gamma1, z, w);
    out += (-1.0 / 4.0)
        * delta(i, j)
        * gamma1.data[u * gamma1.n + x]
        * theta(gamma1, y, w)
        * theta(gamma1, z, v);
    out += (-1.0 / 2.0)
        * delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, y)],
            &[active(spaces, w), active(spaces, x)],
        )
        * theta(gamma1, z, v);
    out += (-1.0 / 2.0)
        * delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, y)],
            &[active(spaces, x), active(spaces, v)],
        )
        * theta(gamma1, z, w);
    out += (-1.0 / 2.0)
        * delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, z)],
            &[active(spaces, v), active(spaces, x)],
        )
        * theta(gamma1, y, w);
    out += delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, z)],
            &[active(spaces, w), active(spaces, x)],
        )
        * theta(gamma1, y, v);
    out += -1.0
        * delta(i, j)
        * lambdas.lambda3.get(
            &[active(spaces, u), active(spaces, y), active(spaces, z)],
            &[active(spaces, w), active(spaces, v), active(spaces, x)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C10`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_aa_to_av_aa_to_av(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (v, a, t, u) = double(left);
    let (z, b, x, y) = double(right);
    let mut out = 0.0;
    out += (1.0 / 2.0)
        * delta(a, b)
        * gamma1.data[t * gamma1.n + x]
        * gamma1.data[u * gamma1.n + y]
        * theta(gamma1, z, v);
    out += (-1.0 / 2.0)
        * delta(a, b)
        * gamma1.data[t * gamma1.n + x]
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, z)],
            &[active(spaces, y), active(spaces, v)],
        );
    out += (-1.0 / 4.0)
        * delta(a, b)
        * gamma1.data[t * gamma1.n + y]
        * gamma1.data[u * gamma1.n + x]
        * theta(gamma1, z, v);
    out += (-1.0 / 2.0)
        * delta(a, b)
        * gamma1.data[t * gamma1.n + y]
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, z)],
            &[active(spaces, v), active(spaces, x)],
        );
    out += (-1.0 / 2.0)
        * delta(a, b)
        * gamma1.data[u * gamma1.n + x]
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, z)],
            &[active(spaces, v), active(spaces, y)],
        );
    out += delta(a, b)
        * gamma1.data[u * gamma1.n + y]
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, z)],
            &[active(spaces, v), active(spaces, x)],
        );
    out += (1.0 / 2.0)
        * delta(a, b)
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, u)],
            &[active(spaces, x), active(spaces, y)],
        )
        * theta(gamma1, z, v);
    out += delta(a, b)
        * lambdas.lambda3.get(
            &[active(spaces, t), active(spaces, u), active(spaces, z)],
            &[active(spaces, v), active(spaces, y), active(spaces, x)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C11`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_aa_to_vv_aa_to_vv(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, b, t, u) = double(left);
    let (c, d, v, w) = double(right);
    let mut out = 0.0;
    out +=
        delta(a, c) * delta(b, d) * gamma1.data[t * gamma1.n + v] * gamma1.data[u * gamma1.n + w];
    out += (-1.0 / 2.0)
        * delta(a, c)
        * delta(b, d)
        * gamma1.data[t * gamma1.n + w]
        * gamma1.data[u * gamma1.n + v];
    out += delta(a, c)
        * delta(b, d)
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, u)],
            &[active(spaces, v), active(spaces, w)],
        );
    out += (-1.0 / 2.0)
        * delta(a, d)
        * delta(b, c)
        * gamma1.data[t * gamma1.n + v]
        * gamma1.data[u * gamma1.n + w];
    out +=
        delta(a, d) * delta(b, c) * gamma1.data[t * gamma1.n + w] * gamma1.data[u * gamma1.n + v];
    out += delta(a, d)
        * delta(b, c)
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, u)],
            &[active(spaces, w), active(spaces, v)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C12`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_aa_to_aa_aa_to_aa(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (q, s, p, r) = double(left);
    let (t, v, u, w) = double(right);
    let mut out = 0.0;
    out += (1.0 / 4.0)
        * gamma1.data[p * gamma1.n + u]
        * gamma1.data[r * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, q), active(spaces, s)],
        );
    out += (1.0 / 4.0)
        * gamma1.data[p * gamma1.n + u]
        * gamma1.data[r * gamma1.n + w]
        * theta(gamma1, t, q)
        * theta(gamma1, v, s);
    out += (-1.0 / 8.0)
        * gamma1.data[p * gamma1.n + u]
        * gamma1.data[r * gamma1.n + w]
        * theta(gamma1, t, s)
        * theta(gamma1, v, q);
    out += (-1.0 / 4.0)
        * gamma1.data[p * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, s), active(spaces, w)],
        )
        * theta(gamma1, v, q);
    out += (-1.0 / 4.0)
        * gamma1.data[p * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, w), active(spaces, q)],
        )
        * theta(gamma1, v, s);
    out += (-1.0 / 4.0)
        * gamma1.data[p * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, q), active(spaces, w)],
        )
        * theta(gamma1, t, s);
    out += (1.0 / 2.0)
        * gamma1.data[p * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, s), active(spaces, w)],
        )
        * theta(gamma1, t, q);
    out += (-1.0 / 2.0)
        * gamma1.data[p * gamma1.n + u]
        * lambdas.lambda3.get(
            &[active(spaces, r), active(spaces, t), active(spaces, v)],
            &[active(spaces, s), active(spaces, q), active(spaces, w)],
        );
    out += (1.0 / 4.0)
        * gamma1.data[p * gamma1.n + w]
        * gamma1.data[r * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, s), active(spaces, q)],
        );
    out += (-1.0 / 8.0)
        * gamma1.data[p * gamma1.n + w]
        * gamma1.data[r * gamma1.n + u]
        * theta(gamma1, t, q)
        * theta(gamma1, v, s);
    out += (1.0 / 4.0)
        * gamma1.data[p * gamma1.n + w]
        * gamma1.data[r * gamma1.n + u]
        * theta(gamma1, t, s)
        * theta(gamma1, v, q);
    out += (-1.0 / 4.0)
        * gamma1.data[p * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, q), active(spaces, u)],
        )
        * theta(gamma1, v, s);
    out += (1.0 / 2.0)
        * gamma1.data[p * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, s), active(spaces, u)],
        )
        * theta(gamma1, v, q);
    out += (-1.0 / 4.0)
        * gamma1.data[p * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, s), active(spaces, u)],
        )
        * theta(gamma1, t, q);
    out += (-1.0 / 4.0)
        * gamma1.data[p * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, u), active(spaces, q)],
        )
        * theta(gamma1, t, s);
    out += (-1.0 / 2.0)
        * gamma1.data[p * gamma1.n + w]
        * lambdas.lambda3.get(
            &[active(spaces, r), active(spaces, t), active(spaces, v)],
            &[active(spaces, s), active(spaces, u), active(spaces, q)],
        );
    out += (-1.0 / 4.0)
        * gamma1.data[r * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, q), active(spaces, w)],
        )
        * theta(gamma1, v, s);
    out += (-1.0 / 4.0)
        * gamma1.data[r * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, w), active(spaces, s)],
        )
        * theta(gamma1, v, q);
    out += (1.0 / 2.0)
        * gamma1.data[r * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, q), active(spaces, w)],
        )
        * theta(gamma1, t, s);
    out += (-1.0 / 4.0)
        * gamma1.data[r * gamma1.n + u]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, s), active(spaces, w)],
        )
        * theta(gamma1, t, q);
    out += (-1.0 / 2.0)
        * gamma1.data[r * gamma1.n + u]
        * lambdas.lambda3.get(
            &[active(spaces, p), active(spaces, t), active(spaces, v)],
            &[active(spaces, q), active(spaces, s), active(spaces, w)],
        );
    out += (1.0 / 2.0)
        * gamma1.data[r * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, q), active(spaces, u)],
        )
        * theta(gamma1, v, s);
    out += (-1.0 / 4.0)
        * gamma1.data[r * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, s), active(spaces, u)],
        )
        * theta(gamma1, v, q);
    out += (-1.0 / 4.0)
        * gamma1.data[r * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, q), active(spaces, u)],
        )
        * theta(gamma1, t, s);
    out += (-1.0 / 4.0)
        * gamma1.data[r * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, u), active(spaces, s)],
        )
        * theta(gamma1, t, q);
    out += (-1.0 / 2.0)
        * gamma1.data[r * gamma1.n + w]
        * lambdas.lambda3.get(
            &[active(spaces, p), active(spaces, t), active(spaces, v)],
            &[active(spaces, q), active(spaces, u), active(spaces, s)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, q), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, s), active(spaces, w)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, q), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, u), active(spaces, s)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, u), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, q), active(spaces, w)],
        );
    out += (1.0 / 3.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, u), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, q), active(spaces, s)],
        );
    out += (1.0 / 6.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, u), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, s), active(spaces, q)],
        );
    out += (1.0 / 4.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, u), active(spaces, w)],
        )
        * theta(gamma1, t, q)
        * theta(gamma1, v, s);
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, w), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, u), active(spaces, q)],
        );
    out += (1.0 / 6.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, w), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, q), active(spaces, s)],
        );
    out += (1.0 / 3.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, w), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, v)],
            &[active(spaces, s), active(spaces, q)],
        );
    out += (1.0 / 4.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, r)],
            &[active(spaces, w), active(spaces, u)],
        )
        * theta(gamma1, t, s)
        * theta(gamma1, v, q);
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, q), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, u), active(spaces, w)],
        );
    out += lambdas.lambda2.get(
        &[active(spaces, p), active(spaces, t)],
        &[active(spaces, q), active(spaces, u)],
    ) * lambdas.lambda2.get(
        &[active(spaces, r), active(spaces, v)],
        &[active(spaces, s), active(spaces, w)],
    );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, q), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, s), active(spaces, u)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, s), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, q), active(spaces, w)],
        );
    out += (1.0 / 3.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, s), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, q), active(spaces, u)],
        );
    out += (1.0 / 6.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, s), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, u), active(spaces, q)],
        );
    out += (1.0 / 6.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, w), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, q), active(spaces, u)],
        );
    out += (1.0 / 3.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, w), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, u), active(spaces, q)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, t)],
            &[active(spaces, w), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, v)],
            &[active(spaces, s), active(spaces, q)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, q), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, w), active(spaces, u)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, q), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, s), active(spaces, w)],
        );
    out += lambdas.lambda2.get(
        &[active(spaces, p), active(spaces, v)],
        &[active(spaces, q), active(spaces, w)],
    ) * lambdas.lambda2.get(
        &[active(spaces, r), active(spaces, t)],
        &[active(spaces, s), active(spaces, u)],
    );
    out += (1.0 / 3.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, s), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, q), active(spaces, w)],
        );
    out += (1.0 / 6.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, s), active(spaces, u)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, w), active(spaces, q)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, s), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, q), active(spaces, u)],
        );
    out += (1.0 / 6.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, u), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, q), active(spaces, w)],
        );
    out += (1.0 / 3.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, u), active(spaces, s)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, w), active(spaces, q)],
        );
    out += (-1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, p), active(spaces, v)],
            &[active(spaces, u), active(spaces, w)],
        )
        * lambdas.lambda2.get(
            &[active(spaces, r), active(spaces, t)],
            &[active(spaces, s), active(spaces, q)],
        );
    out += (1.0 / 2.0)
        * lambdas.lambda3.get(
            &[active(spaces, p), active(spaces, r), active(spaces, t)],
            &[active(spaces, q), active(spaces, w), active(spaces, u)],
        )
        * theta(gamma1, v, s);
    out += (1.0 / 2.0)
        * lambdas.lambda3.get(
            &[active(spaces, p), active(spaces, r), active(spaces, t)],
            &[active(spaces, w), active(spaces, s), active(spaces, u)],
        )
        * theta(gamma1, v, q);
    out += (1.0 / 2.0)
        * lambdas.lambda3.get(
            &[active(spaces, p), active(spaces, r), active(spaces, v)],
            &[active(spaces, q), active(spaces, u), active(spaces, w)],
        )
        * theta(gamma1, t, s);
    out += (1.0 / 2.0)
        * lambdas.lambda3.get(
            &[active(spaces, p), active(spaces, r), active(spaces, v)],
            &[active(spaces, u), active(spaces, s), active(spaces, w)],
        )
        * theta(gamma1, t, q);
    out += lambdas.lambda4.get(
        &[
            active(spaces, p),
            active(spaces, r),
            active(spaces, t),
            active(spaces, v),
        ],
        &[
            active(spaces, q),
            active(spaces, s),
            active(spaces, u),
            active(spaces, w),
        ],
    );
    out
}

/// Evaluate generated Appendix-C overlap block `C13`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_a_to_v_aa_to_av(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, u) = single(left);
    let (x, b, v, w) = double(right);
    let mut out = 0.0;
    out += delta(a, b)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, x)],
            &[active(spaces, w), active(spaces, v)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C14`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_c_to_a_ca_to_aa(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (u, i) = single(left);
    let (w, x, j, v) = double(right);
    let mut out = 0.0;
    out += -1.0
        * delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, w), active(spaces, x)],
            &[active(spaces, u), active(spaces, v)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C15`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_a_to_a_aa_to_aa(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (u, t) = single(left);
    let (y, z, w, x) = double(right);
    let mut out = 0.0;
    out += (-1.0 / 2.0)
        * gamma1.data[t * gamma1.n + w]
        * lambdas.lambda2.get(
            &[active(spaces, y), active(spaces, z)],
            &[active(spaces, u), active(spaces, x)],
        );
    out += (-1.0 / 2.0)
        * gamma1.data[t * gamma1.n + x]
        * lambdas.lambda2.get(
            &[active(spaces, y), active(spaces, z)],
            &[active(spaces, w), active(spaces, u)],
        );
    out += (1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, y)],
            &[active(spaces, x), active(spaces, w)],
        )
        * theta(gamma1, z, u);
    out += (1.0 / 2.0)
        * lambdas.lambda2.get(
            &[active(spaces, t), active(spaces, z)],
            &[active(spaces, w), active(spaces, x)],
        )
        * theta(gamma1, y, u);
    out += lambdas.lambda3.get(
        &[active(spaces, t), active(spaces, y), active(spaces, z)],
        &[active(spaces, u), active(spaces, w), active(spaces, x)],
    );
    out
}

/// Evaluate generated Appendix-C overlap block `C16`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_ca_to_av_ca_to_va(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (w, a, i, u) = double(left);
    let (b, y, j, x) = double(right);
    let mut out = 0.0;
    out += (-1.0 / 2.0)
        * delta(a, b)
        * delta(i, j)
        * gamma1.data[u * gamma1.n + x]
        * theta(gamma1, y, w);
    out += -1.0
        * delta(a, b)
        * delta(i, j)
        * lambdas.lambda2.get(
            &[active(spaces, u), active(spaces, y)],
            &[active(spaces, w), active(spaces, x)],
        );
    out
}

/// Evaluate generated Appendix-C overlap block `C17`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_c_to_v_c_to_v(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, i) = single(left);
    let (b, j) = single(right);
    let mut out = 0.0;
    out += 2.0 * delta(a, b) * delta(i, j);
    out
}

/// Evaluate generated Appendix-C overlap block `C18`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_c_to_v_ca_to_av(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, i) = single(left);
    let (x, b, j, w) = double(right);
    let mut out = 0.0;
    out
}

/// Evaluate generated Appendix-C overlap block `C19`.
/// # Arguments:
/// - `left`: Left excitation operator, daggered in the metric element.
/// - `right`: Right excitation operator.
/// - `spaces`: Core, active, and virtual orbital-space maps.
/// - `gamma1`: Spin-free one-particle RDM.
/// - `lambdas`: Spin-free active-space cumulants.
/// # Returns:
/// - `f64`: Raw FOIS overlap metric element.
#[allow(unused_variables)]
pub(crate) fn overlap_c_to_v_ca_to_va(
    left: Excitation,
    right: Excitation,
    spaces: &Spaces,
    gamma1: &RDM1<f64>,
    lambdas: &Cumulants<f64>,
) -> f64 {
    let (a, i) = single(left);
    let (b, x, j, w) = double(right);
    let mut out = 0.0;
    out
}
