// basis/types.rs

use crate::{HSCFState, SCFState};

/// Real and holomorphic determinant states generated for a reference-basis request.
pub struct ReferenceBasis {
    /// Real SCF states generated by MOM or metadynamics.
    pub states: Vec<SCFState>,
    /// Complex h-SCF states plus promoted real states when holomorphic recipes are present.
    pub hstates: Vec<HSCFState>,
}
