from core import *
from specs import A, C, V
from canonical import lambdaRank, canonicalTensor, canonicaliseTensorSymmetry
from spinsum import invPerm, composePerm, cycleCountPerm, spinGram

def G(p: Idx, q: Idx) -> Expr:
    return tensor("Gamma1", (p,), (q,))

def T(p: Idx, q: Idx) -> Expr:
    return tensor("Theta", (p,), (q,))

def D(p: Idx, q: Idx) -> Expr:
    return delta(p, q)

def L2(p: Idx, q: Idx, r: Idx, s: Idx) -> Expr:
    return tensor("Lambda2", (p, q), (r, s))

def L3(p: Idx, q: Idx, r: Idx, s: Idx, t: Idx, u: Idx) -> Expr:
    return tensor("Lambda3", (p, q, r), (s, t, u))

def L4(
    p: Idx,
    q: Idx,
    r: Idx,
    s: Idx,
    t: Idx,
    u: Idx,
    v: Idx,
    w: Idx,
) -> Expr:
    return tensor("Lambda4", (p, q, r, s), (t, u, v, w))

def orbitProjectsToZero(rank: int, coeffs: dict[tuple[int, ...], Fraction]) -> bool:
    """Return True if a Lambda rank-k orbit lies in the spin-null space.

    Notation:
        G c = 0

    Examples:
        For rank 3 this recognises

            \sum_{\pi \in S_3} \Lambda^{pqr}_{\pi(abc)} = 0

        For rank 4 it recognises the corresponding Lambda4 spin-null
        relations generated by the rank-4 spin-projection Gram matrix.
    """
    perms = tuple(permutations(range(rank)))
    gram = spinGram(rank)

    for i, _p in enumerate(perms):
        lhs = Fraction(0)

        for j, q in enumerate(perms):
            lhs += gram[i][j] * coeffs.get(q, Fraction(0))

        if lhs != 0:
            return False

    return True

def reduceSpinNull(expr: Expr) -> Expr:
    """Remove Lambda3/Lambda4 spin-null orbit differences for tests.

    Notation:
        Two expressions are equal if their difference lies in the spin-null
        space of the corresponding spin-free cumulant projection.

    Examples:
        Lambda3 full lower-permutation orbit is removed.

        Lambda4 null combinations are removed by the same G c = 0 condition.

    This is not a block-specific rule. It applies to any Lambda3 or Lambda4
    term with fixed upper indices, fixed lower-index set, and fixed surrounding
    scalar factors.
    """
    grouped: dict[tuple, dict[tuple[int, ...], Fraction]] = {}
    passthrough = []

    for term in expr:
        high = [
            tensorIn
            for tensorIn in term.tensors
            if lambdaRank(tensorIn.name) in (3, 4)
        ]

        if len(high) != 1:
            passthrough.append(term)
            continue

        lam = high[0]
        rank = lambdaRank(lam.name)

        if rank is None:
            passthrough.append(term)
            continue

        if len(lam.upper) != rank or len(lam.lower) != rank:
            passthrough.append(term)
            continue

        if len(set(lam.lower)) != rank:
            passthrough.append(term)
            continue

        lowerBase = tuple(sorted(lam.lower))
        lowerPerm = tuple(
            lowerBase.index(idx)
            for idx in lam.lower
        )

        otherTensors = []
        removed = False

        for tensorIn in term.tensors:
            if tensorIn == lam and not removed:
                removed = True
                continue

            otherTensors.append(tensorIn)

        key = (
            rank,
            term.deltas,
            tuple(otherTensors),
            lam.name,
            lam.upper,
            lowerBase,
        )

        if key not in grouped:
            grouped[key] = {}

        grouped[key][lowerPerm] = grouped[key].get(lowerPerm, Fraction(0)) + term.coeff

    out = list(passthrough)

    for key, coeffs in grouped.items():
        rank, deltas, otherTensors, name, upper, lowerBase = key

        if orbitProjectsToZero(rank, coeffs):
            continue

        for perm, coeff in sorted(coeffs.items()):
            if coeff == 0:
                continue

            out.append(
                Term(
                    coeff = coeff,
                    deltas = deltas,
                    tensors = tuple(sorted(
                        otherTensors
                        + (
                            Tensor(
                                name,
                                upper,
                                tuple(lowerBase[i] for i in perm),
                            ),
                        )
                    )),
                )
            )

    return combine(tuple(out))

def normalForm(expr: Expr) -> Expr:
    return reduceSpinNull(
        canonicaliseTensorSymmetry(
            combine(expr)
        )
    )

def isExpr(value) -> bool:
    return isinstance(value, tuple) and all(
        isinstance(term, Term)
        for term in value
    )

def assertEq(got, want, label: str) -> None:
    if isExpr(got) and isExpr(want):
        diff = normalForm(
            add(
                got,
                scale(want, Fraction(-1, 1)),
            )
        )

        if diff:
            print(f"===== {label} got =====")
            print(got)
            print(f"===== {label} want =====")
            print(want)
            print(f"===== {label} diff =====")
            print(diff)
            raise SystemExit(1)

        return

    if got != want:
        print(f"===== {label} got =====")
        print(got)
        print(f"===== {label} want =====")
        print(want)
        raise SystemExit(1)

def checkCar() -> None:
    u = A("u")
    v = A("v")

    assertEq(
        anticommutator(
            Op("annihilate", u, ALPHA, 0),
            Op("create", v, ALPHA, 1),
        ),
        delta(u, v),
        "CAR same spin",
    )

    assertEq(
        anticommutator(
            Op("annihilate", u, ALPHA, 0),
            Op("create", v, BETA, 1),
        ),
        zero(),
        "CAR opposite spin",
    )

def checkFrozenReference() -> None:
    ref = Ref()
    i = C("i")
    j = C("j")
    a = V("a")
    b = V("b")

    assertEq(
        ref.frozenPair(
            Op("create", i, ALPHA, 0),
            Op("annihilate", j, ALPHA, 1),
        ),
        delta(i, j),
        "core occupied pair",
    )

    assertEq(
        ref.frozenPair(
            Op("annihilate", a, ALPHA, 0),
            Op("create", b, ALPHA, 1),
        ),
        delta(a, b),
        "virtual empty pair",
    )

def checkSpinExpansion() -> None:
    i = C("i")
    j = C("j")
    u = A("u")
    v = A("v")

    assertEq(
        len(groupE1(u, v, 0).strings),
        2,
        "E1 spin expansion length",
    )

    assertEq(
        len(groupE2(u, v, i, j, 0).strings),
        4,
        "E2 spin expansion length",
    )

def checkActiveOneBody() -> None:
    ref = Ref()
    u = A("u")
    v = A("v")

    assertEq(
        ref.kappa((
            Op("create", u, ALPHA, 0),
            Op("annihilate", v, ALPHA, 1),
        )),
        scale(G(u, v), Fraction(1, 2)),
        "active particle RDM alpha",
    )

    assertEq(
        ref.kappa((
            Op("annihilate", u, ALPHA, 0),
            Op("create", v, ALPHA, 1),
        )),
        scale(T(v, u), Fraction(1, 2)),
        "active hole RDM alpha",
    )

    assertEq(
        ref.kappa((
            Op("annihilate", u, ALPHA, 0),
            Op("create", v, BETA, 1),
        )),
        zero(),
        "active hole RDM opposite spin",
    )

def checkSpinReplacement() -> None:
    p = A("p")
    q = A("q")
    r = A("r")
    s = A("s")

    assertEq(
        Spin.projectCumulant(
            1,
            (p,),
            (r,),
            (ALPHA,),
            (ALPHA,),
        ),
        scale(G(p, r), Fraction(1, 2)),
        "Gamma1 alpha alpha",
    )

    assertEq(
        Spin.projectCumulant(
            1,
            (p,),
            (r,),
            (ALPHA,),
            (BETA,),
        ),
        zero(),
        "Gamma1 alpha beta",
    )

    assertEq(
        Spin.projectCumulant(
            2,
            (p, q),
            (r, s),
            (ALPHA, ALPHA),
            (ALPHA, ALPHA),
        ),
        add(
            scale(L2(p, q, r, s), Fraction(1, 6)),
            scale(L2(p, q, s, r), Fraction(-1, 6)),
        ),
        "Lambda2 alpha alpha / alpha alpha",
    )

    assertEq(
        Spin.projectCumulant(
            2,
            (p, q),
            (r, s),
            (ALPHA, BETA),
            (ALPHA, BETA),
        ),
        add(
            scale(L2(p, q, r, s), Fraction(2, 6)),
            scale(L2(p, q, s, r), Fraction(1, 6)),
        ),
        "Lambda2 alpha beta / alpha beta",
    )

    assertEq(
        Spin.projectCumulant(
            2,
            (p, q),
            (r, s),
            (ALPHA, BETA),
            (BETA, ALPHA),
        ),
        add(
            scale(L2(p, q, r, s), Fraction(-1, 6)),
            scale(L2(p, q, s, r), Fraction(-2, 6)),
        ),
        "Lambda2 alpha beta / beta alpha",
    )

def checkWick() -> None:
    ref = Ref()
    wick = Wick(ref)
    u = A("u")
    v = A("v")

    assertEq(
        wick.eval(Product((tau1(u, v, 0),))),
        zero(),
        "single GNO group expectation",
    )

def checkC1() -> None:
    ref = Ref()
    wick = Wick(ref)
    i = C("i")
    j = C("j")
    u = A("u")
    v = A("v")

    assertEq(
        wick.eval(Product((
            tau1(i, u, 0),
            tau1(v, j, 1),
        ))),
        mul(
            delta(i, j),
            T(v, u),
        ),
        "C1",
    )

def checkC2() -> None:
    ref = Ref()
    wick = Wick(ref)

    a = V("a")
    b = V("b")
    t = A("t")
    u = A("u")

    assertEq(
        wick.eval(Product((
            tau1(t, a, 0),
            tau1(b, u, 1),
        ))),
        mul(
            delta(a, b),
            G(t, u),
        ),
        "C2",
    )

def checkC3() -> None:
    ref = Ref()
    wick = Wick(ref)

    u = A("u")
    v = A("v")
    w = A("w")
    x = A("x")

    assertEq(
        wick.eval(Product((
            tau1(u, v, 0),
            tau1(x, w, 1),
        ))),
        add(
            scale(
                mul(
                    G(u, w),
                    T(x, v),
                ),
                Fraction(1, 2),
            ),
            L2(u, x, v, w),
        ),
        "C3",
    )

def checkC4() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    a = V("a")
    b = V("b")
    u = A("u")
    v = A("v")
    w = A("w")
    x = A("x")

    assertEq(
        wick.eval(Product((
            groupE2(i, u, v, a, 0),
            groupE2(x, b, j, w, 1),
        ))),
        mul(
            delta(a, b),
            mul(
                delta(i, j),
                add(
                    mul(
                        G(u, w),
                        T(x, v),
                    ),
                    scale(
                        L2(u, x, w, v),
                        Fraction(-1, 1),
                    ),
                ),
            ),
        ),
        "C4",
    )

def checkC5() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    a = V("a")
    b = V("b")
    u = A("u")
    v = A("v")
    w = A("w")
    x = A("x")

    assertEq(
        wick.eval(Product((
            groupE2(i, u, a, v, 0),
            groupE2(b, x, j, w, 1),
        ))),
        mul(
            delta(a, b),
            mul(
                delta(i, j),
                add(
                    mul(
                        G(u, w),
                        T(x, v),
                    ),
                    scale(
                        L2(u, x, v, w),
                        Fraction(2, 1),
                    ),
                ),
            ),
        ),
        "C5",
    )

def checkC6() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    a = V("a")
    b = V("b")
    c = V("c")
    d = V("d")
    u = A("u")
    v = A("v")

    assertEq(
        wick.eval(Product((
            groupE2(i, u, a, b, 0),
            groupE2(c, d, j, v, 1),
        ))),
        add(
            scale(
                prod((
                    D(a, c),
                    D(b, d),
                    D(i, j),
                    G(u, v),
                )),
                2,
            ),
            scale(
                prod((
                    D(a, d),
                    D(b, c),
                    D(i, j),
                    G(u, v),
                )),
                -1,
            ),
        ),
        "C6",
    )

def checkC7() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    k = C("k")
    l = C("l")
    a = V("a")
    b = V("b")
    u = A("u")
    v = A("v")

    assertEq(
        wick.eval(Product((
            groupE2(i, j, u, a, 0),
            groupE2(v, b, k, l, 1),
        ))),
        add(
            scale(
                prod((
                    D(a, b),
                    D(i, k),
                    D(j, l),
                    T(v, u),
                )),
                2,
            ),
            scale(
                prod((
                    D(a, b),
                    D(i, l),
                    D(j, k),
                    T(v, u),
                )),
                -1,
            ),
        ),
        "C7",
    )

def checkC8() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    k = C("k")
    l = C("l")
    u = A("u")
    v = A("v")
    w = A("w")
    x = A("x")

    assertEq(
        wick.eval(Product((
            groupE2(i, j, u, v, 0),
            groupE2(w, x, k, l, 1),
        ))),
        add(
            prod((
                D(i, k),
                D(j, l),
                L2(w, x, u, v),
            )),
            prod((
                D(i, k),
                D(j, l),
                T(w, u),
                T(x, v),
            )),
            scale(
                prod((
                    D(i, k),
                    D(j, l),
                    T(w, v),
                    T(x, u),
                )),
                Fraction(-1, 2),
            ),
            prod((
                D(i, l),
                D(j, k),
                L2(w, x, v, u),
            )),
            scale(
                prod((
                    D(i, l),
                    D(j, k),
                    T(w, u),
                    T(x, v),
                )),
                Fraction(-1, 2),
            ),
            prod((
                D(i, l),
                D(j, k),
                T(w, v),
                T(x, u),
            )),
        ),
        "C8",
    )

def checkC9() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    u = A("u")
    v = A("v")
    w = A("w")
    x = A("x")
    y = A("y")
    z = A("z")

    assertEq(
        wick.eval(Product((
            groupE2(i, u, v, w, 0),
            groupE2(y, z, j, x, 1),
        ))),
        mul(
            D(i, j),
            add(
                scale(
                    mul(
                        G(u, x),
                        L2(y, z, v, w),
                    ),
                    Fraction(1, 2),
                ),
                scale(
                    prod((
                        G(u, x),
                        T(y, v),
                        T(z, w),
                    )),
                    Fraction(1, 2),
                ),
                scale(
                    prod((
                        G(u, x),
                        T(y, w),
                        T(z, v),
                    )),
                    Fraction(-1, 4),
                ),
                scale(
                    mul(
                        L2(u, y, w, x),
                        T(z, v),
                    ),
                    Fraction(-1, 2),
                ),
                scale(
                    mul(
                        L2(u, y, x, v),
                        T(z, w),
                    ),
                    Fraction(-1, 2),
                ),
                scale(
                    mul(
                        L2(u, z, v, x),
                        T(y, w),
                    ),
                    Fraction(-1, 2),
                ),
                mul(
                    L2(u, z, w, x),
                    T(y, v),
                ),
                scale(
                    L3(u, y, z, w, v, x),
                    Fraction(-1, 1),
                ),
            ),
        ),
        "C9",
    )

def checkC10() -> None:
    ref = Ref()
    wick = Wick(ref)

    a = V("a")
    b = V("b")
    t = A("t")
    u = A("u")
    v = A("v")
    x = A("x")
    y = A("y")
    z = A("z")

    assertEq(
        wick.eval(Product((
            groupE2(t, u, v, a, 0),
            groupE2(z, b, x, y, 1),
        ))),
        mul(
            D(a, b),
            add(
                scale(
                    prod((
                        G(t, x),
                        G(u, y),
                        T(z, v),
                    )),
                    Fraction(1, 2),
                ),
                scale(
                    mul(
                        G(t, x),
                        L2(u, z, y, v),
                    ),
                    Fraction(-1, 2),
                ),
                scale(
                    prod((
                        G(t, y),
                        G(u, x),
                        T(z, v),
                    )),
                    Fraction(-1, 4),
                ),
                scale(
                    mul(
                        G(t, y),
                        L2(u, z, v, x),
                    ),
                    Fraction(-1, 2),
                ),
                scale(
                    mul(
                        G(u, x),
                        L2(t, z, v, y),
                    ),
                    Fraction(-1, 2),
                ),
                mul(
                    G(u, y),
                    L2(t, z, v, x),
                ),
                scale(
                    mul(
                        L2(t, u, x, y),
                        T(z, v),
                    ),
                    Fraction(1, 2),
                ),
                L3(t, u, z, v, y, x),
            ),
        ),
        "C10",
    )

def checkC11() -> None:
    ref = Ref()
    wick = Wick(ref)

    a = V("a")
    b = V("b")
    c = V("c")
    d = V("d")
    t = A("t")
    u = A("u")
    v = A("v")
    w = A("w")

    assertEq(
        wick.eval(Product((
            groupE2(t, u, a, b, 0),
            groupE2(c, d, v, w, 1),
        ))),
        add(
            prod((
                D(a, c),
                D(b, d),
                G(t, v),
                G(u, w),
            )),
            scale(
                prod((
                    D(a, c),
                    D(b, d),
                    G(t, w),
                    G(u, v),
                )),
                Fraction(-1, 2),
            ),
            prod((
                D(a, c),
                D(b, d),
                L2(t, u, v, w),
            )),
            scale(
                prod((
                    D(a, d),
                    D(b, c),
                    G(t, v),
                    G(u, w),
                )),
                Fraction(-1, 2),
            ),
            prod((
                D(a, d),
                D(b, c),
                G(t, w),
                G(u, v),
            )),
            prod((
                D(a, d),
                D(b, c),
                L2(t, u, w, v),
            )),
        ),
        "C11",
    )

def checkC12() -> None:
    ref = Ref()
    wick = Wick(ref)

    p = A("p")
    q = A("q")
    r = A("r")
    s = A("s")
    t = A("t")
    u = A("u")
    v = A("v")
    w = A("w")

    def M(*factors: Expr) -> Expr:
        return prod(factors)

    def C(numerator: int, denominator: int, *factors: Expr) -> Expr:
        return scale(
            M(*factors),
            Fraction(numerator, denominator),
        )

    assertEq(
        wick.eval(Product((
            groupE2(p, r, q, s, 0),
            groupE2(t, v, u, w, 1),
        ))),
        add(
            L4(p, r, t, v, q, s, u, w),

            C(1, 2, T(v, s), L3(p, r, t, q, w, u)),
            C(1, 2, T(v, q), L3(p, r, t, w, s, u)),
            C(1, 2, T(t, s), L3(p, r, v, q, u, w)),
            C(1, 2, T(t, q), L3(p, r, v, u, s, w)),

            C(-1, 2, G(r, u), L3(p, t, v, q, s, w)),
            C(-1, 2, G(r, w), L3(p, t, v, q, u, s)),
            C(-1, 2, G(p, u), L3(r, t, v, s, q, w)),
            C(-1, 2, G(p, w), L3(r, t, v, s, u, q)),

            C(1, 4, T(t, q), T(v, s), add(
                M(G(p, u), G(r, w)),
                C(-1, 2, G(p, w), G(r, u)),
                L2(p, r, u, w),
            )),

            C(1, 4, T(t, s), T(v, q), add(
                M(G(p, w), G(r, u)),
                C(-1, 2, G(p, u), G(r, w)),
                L2(p, r, w, u),
            )),

            C(1, 4, G(p, u), G(r, w), L2(t, v, q, s)),
            C(1, 4, G(p, w), G(r, u), L2(t, v, s, q)),

            C(1, 3, L2(t, v, q, s), L2(p, r, u, w)),
            C(1, 3, L2(t, v, s, q), L2(p, r, w, u)),
            C(1, 6, L2(t, v, q, s), L2(p, r, w, u)),
            C(1, 6, L2(t, v, s, q), L2(p, r, u, w)),

            C(1, 2, T(v, s), G(r, w), L2(p, t, q, u)),
            C(-1, 4, T(v, s), G(r, u), L2(p, t, q, w)),
            C(-1, 4, T(v, q), G(r, w), L2(p, t, s, u)),
            C(-1, 4, T(v, q), G(r, u), L2(p, t, w, s)),

            C(-1, 4, T(t, s), G(r, w), L2(p, v, q, u)),
            C(1, 2, T(t, s), G(r, u), L2(p, v, q, w)),
            C(-1, 4, T(t, q), G(r, w), L2(p, v, u, s)),
            C(-1, 4, T(t, q), G(r, u), L2(p, v, s, w)),

            C(-1, 4, T(v, s), G(p, w), L2(r, t, q, u)),
            C(-1, 4, T(v, s), G(p, u), L2(r, t, w, q)),
            C(1, 2, T(v, q), G(p, w), L2(r, t, s, u)),
            C(-1, 4, T(v, q), G(p, u), L2(r, t, s, w)),

            C(-1, 4, T(t, s), G(p, w), L2(r, v, u, q)),
            C(-1, 4, T(t, s), G(p, u), L2(r, v, q, w)),
            C(-1, 4, T(t, q), G(p, w), L2(r, v, s, u)),
            C(1, 2, T(t, q), G(p, u), L2(r, v, s, w)),

            C(-1, 2, L2(p, r, w, s), L2(t, v, u, q)),
            C(-1, 2, L2(p, r, u, s), L2(t, v, q, w)),
            C(-1, 2, L2(p, r, q, w), L2(t, v, u, s)),
            C(-1, 2, L2(p, r, q, u), L2(t, v, s, w)),

            C(-1, 2, L2(t, r, q, s), L2(p, v, u, w)),
            C(-1, 2, L2(t, r, u, w), L2(p, v, q, s)),
            C(-1, 2, L2(v, r, q, s), L2(t, p, u, w)),
            C(-1, 2, L2(p, t, q, s), L2(r, v, u, w)),

            M(L2(r, v, s, w), L2(p, t, q, u)),
            M(L2(r, t, s, u), L2(p, v, q, w)),

            C(-1, 2, L2(r, v, s, u), L2(p, t, q, w)),
            C(-1, 2, L2(r, v, q, w), L2(p, t, s, u)),
            C(-1, 2, L2(p, v, q, u), L2(r, t, s, w)),
            C(-1, 2, L2(r, t, q, u), L2(p, v, s, w)),

            C(1, 3, L2(r, v, q, u), L2(p, t, s, w)),
            C(1, 3, L2(r, v, u, q), L2(p, t, w, s)),
            C(1, 6, L2(r, v, u, q), L2(p, t, s, w)),
            C(1, 6, L2(r, v, q, u), L2(p, t, w, s)),

            C(1, 3, L2(r, t, q, w), L2(p, v, s, u)),
            C(1, 3, L2(r, t, w, q), L2(p, v, u, s)),
            C(1, 6, L2(r, t, w, q), L2(p, v, s, u)),
            C(1, 6, L2(r, t, q, w), L2(p, v, u, s)),
        ),
        "C12",
    )

def checkC13() -> None:
    ref = Ref()
    wick = Wick(ref)

    a = V("a")
    b = V("b")
    u = A("u")
    v = A("v")
    w = A("w")
    x = A("x")

    assertEq(
        wick.eval(Product((
            tau1(u, a, 0),
            groupE2(x, b, v, w, 1),
        ))),
        mul(
            delta(a, b),
            L2(u, x, w, v),
        ),
        "C13",
    )

def checkC14() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    u = A("u")
    v = A("v")
    w = A("w")
    x = A("x")

    assertEq(
        wick.eval(Product((
            tau1(i, u, 0),
            groupE2(w, x, j, v, 1),
        ))),
        scale(
            mul(
                delta(i, j),
                L2(w, x, u, v),
            ),
            Fraction(-1, 1),
        ),
        "C14",
    )

def checkC15() -> None:
    ref = Ref()
    wick = Wick(ref)

    t = A("t")
    u = A("u")
    w = A("w")
    x = A("x")
    y = A("y")
    z = A("z")

    assertEq(
        wick.eval(Product((
            tau1(t, u, 0),
            groupE2(y, z, w, x, 1),
        ))),
        add(
            scale(
                mul(
                    G(t, w),
                    L2(y, z, u, x),
                ),
                Fraction(-1, 2),
            ),
            scale(
                mul(
                    G(t, x),
                    L2(y, z, w, u),
                ),
                Fraction(-1, 2),
            ),
            scale(
                mul(
                    L2(t, y, x, w),
                    T(z, u),
                ),
                Fraction(1, 2),
            ),
            scale(
                mul(
                    L2(t, z, w, x),
                    T(y, u),
                ),
                Fraction(1, 2),
            ),
            L3(t, y, z, u, w, x),
        ),
        "C15",
    )

def checkC16() -> None:
    ref = Ref()
    wick = Wick(ref)

    i = C("i")
    j = C("j")
    a = V("a")
    b = V("b")
    u = A("u")
    w = A("w")
    x = A("x")
    y = A("y")

    assertEq(
        wick.eval(Product((
            groupE2(i, u, w, a, 0),
            groupE2(b, y, j, x, 1),
        ))),
        scale(
            mul(
                delta(a, b),
                mul(
                    delta(i, j),
                    add(
                        scale(
                            mul(
                                G(u, x),
                                T(y, w),
                            ),
                            Fraction(1, 2),
                        ),
                        L2(u, y, w, x),
                    ),
                ),
            ),
            Fraction(-1, 1),
        ),
        "C16",
    )

def checkSpinProjectionSystem() -> None:
    def invPerm(p: tuple[int, ...]) -> tuple[int, ...]:
        out = [0] * len(p)

        for i, x in enumerate(p):
            out[x] = i

        return tuple(out)

    def compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
        return tuple(p[q[i]] for i in range(len(p)))

    def cycleCount(p: tuple[int, ...]) -> int:
        seen = [False] * len(p)
        cycles = 0

        for i in range(len(p)):
            if seen[i]:
                continue

            cycles += 1
            j = i

            while not seen[j]:
                seen[j] = True
                j = p[j]

        return cycles

    for rank in (2, 3, 4):
        perms = tuple(permutations(range(rank)))

        for upperSpins in cartesianProduct(SPINS, repeat = rank):
            for lowerSpins in cartesianProduct(SPINS, repeat = rank):
                coeffs = dict(Spin.coeffs(rank, upperSpins, lowerSpins))

                for p in perms:
                    lhs = Fraction(0)

                    for q in perms:
                        rel = compose(invPerm(p), q)
                        lhs += (
                            coeffs.get(q, Fraction(0))
                            * permutationSign(p)
                            * permutationSign(q)
                            * Fraction(2 ** cycleCount(rel), 1)
                        )

                    rhs = (
                        Fraction(permutationSign(p), 1)
                        if all(upperSpins[i] == lowerSpins[p[i]] for i in range(rank))
                        else Fraction(0)
                    )

                    assertEq(
                        lhs,
                        rhs,
                        f"spin projection system rank {rank} {upperSpins} {lowerSpins} {p}",
                    )

def main() -> None:
    checkCar()
    checkFrozenReference()
    checkSpinExpansion()
    checkActiveOneBody()
    checkSpinReplacement()
    checkWick()
    checkC1()
    checkC2()
    checkC3()
    checkC4()
    checkC5()
    checkC6()
    checkC7()
    checkC8()
    checkC9()
    checkC10()
    checkC11()
    checkC12()
    checkC13()
    checkC14()
    checkC15()
    checkC16()
    checkSpinProjectionSystem()
    print("Tests pass.")

if __name__ == "__main__":
    main()
