// noci/cumulants/cumulants3.rs
// This file is generated by tools/wick/cumulants.py.
// Do not edit generated cumulant expressions by hand.

use super::common::CumulantTensor;
use super::cumulants1::Cumulant1;
use super::cumulants2::Cumulant2;
use crate::noci::rdm::RDM3;
use crate::noci::types::NOCIScalar;

pub(crate) type Cumulant3<T> = CumulantTensor<T>;

/// Build the active-space spin-free three-cumulant.
/// # Arguments:
/// - `gamma3`: Active-space spin-free three-body RDM.
/// - `lambda1`: Active-space one-cumulant.
/// - `lambda2`: Active-space two-cumulant.
/// # Returns:
/// - `Cumulant3<T>`: Active-space three-cumulant.
pub(crate) fn cumulants3<T: NOCIScalar>(
    gamma3: &RDM3<T>,
    lambda1: &Cumulant1<T>,
    lambda2: &Cumulant2<T>,
) -> Cumulant3<T> {
    let n = gamma3.n;
    let mut lambda = CumulantTensor::zeros(3, n);

    for p in 0..n {
        for q in 0..n {
            for r in 0..n {
                for s in 0..n {
                    for t in 0..n {
                        for u in 0..n {
                            let g3i = ((((p * gamma3.n + q) * gamma3.n + r) * gamma3.n + s)
                                * gamma3.n
                                + t)
                                * gamma3.n
                                + u;

                            let disconnected = lambda1.get(&[p], &[s])
                                * lambda1.get(&[q], &[t])
                                * lambda1.get(&[r], &[u])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[p], &[s])
                                    * lambda1.get(&[q], &[u])
                                    * lambda1.get(&[r], &[t])
                                + lambda1.get(&[p], &[s]) * lambda2.get(&[q, r], &[t, u])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[p], &[t])
                                    * lambda1.get(&[q], &[s])
                                    * lambda1.get(&[r], &[u])
                                + <T as From<f64>>::from(1.0 / 4.0)
                                    * lambda1.get(&[p], &[t])
                                    * lambda1.get(&[q], &[u])
                                    * lambda1.get(&[r], &[s])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[p], &[t])
                                    * lambda2.get(&[q, r], &[s, u])
                                + <T as From<f64>>::from(1.0 / 4.0)
                                    * lambda1.get(&[p], &[u])
                                    * lambda1.get(&[q], &[s])
                                    * lambda1.get(&[r], &[t])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[p], &[u])
                                    * lambda1.get(&[q], &[t])
                                    * lambda1.get(&[r], &[s])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[p], &[u])
                                    * lambda2.get(&[q, r], &[t, s])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[q], &[s])
                                    * lambda2.get(&[p, r], &[t, u])
                                + lambda1.get(&[q], &[t]) * lambda2.get(&[p, r], &[s, u])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[q], &[u])
                                    * lambda2.get(&[p, r], &[s, t])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[r], &[s])
                                    * lambda2.get(&[p, q], &[u, t])
                                - <T as From<f64>>::from(1.0 / 2.0)
                                    * lambda1.get(&[r], &[t])
                                    * lambda2.get(&[p, q], &[s, u])
                                + lambda1.get(&[r], &[u]) * lambda2.get(&[p, q], &[s, t]);

                            lambda.set(&[p, q, r], &[s, t, u], gamma3.data[g3i] - disconnected);
                        }
                    }
                }
            }
        }
    }

    lambda
}
