// noci/cumulants/cumulants2.rs
// This file is generated by tools/wick/cumulants.py.
// Do not edit generated cumulant expressions by hand.

use super::common::CumulantTensor;
use super::cumulants1::Cumulant1;
use crate::noci::rdm::RDM2;
use crate::noci::types::NOCIScalar;

pub(crate) type Cumulant2<T> = CumulantTensor<T>;

/// Build the active-space spin-free two-cumulant.
/// # Arguments:
/// - `gamma2`: Full-space spin-free two-body RDM.
/// - `lambda1`: Active-space one-cumulant.
/// - `active`: Active orbital indices in the full NO basis.
/// # Returns:
/// - `Cumulant2<T>`: Active-space two-cumulant.
pub(crate) fn cumulants2<T: NOCIScalar>(
    gamma2: &RDM2<T>,
    lambda1: &Cumulant1<T>,
    active: &[usize],
) -> Cumulant2<T> {
    let n = active.len();
    let mut lambda = CumulantTensor::zeros(2, n);

    for p in 0..n {
        for q in 0..n {
            for r in 0..n {
                for s in 0..n {
                    let pp = active[p];
                    let qq = active[q];
                    let rr = active[r];
                    let ss = active[s];
                    let g2i = ((pp * gamma2.n + qq) * gamma2.n + rr) * gamma2.n + ss;

                    let disconnected = lambda1.get(&[p], &[r]) * lambda1.get(&[q], &[s])
                        - <T as From<f64>>::from(1.0 / 2.0)
                            * lambda1.get(&[p], &[s])
                            * lambda1.get(&[q], &[r]);

                    lambda.set(&[p, q], &[r, s], gamma2.data[g2i] - disconnected);
                }
            }
        }
    }

    lambda
}
