// main.rs 
use std::time::Instant;
use std::process::Command;
use std::fs::File;
use std::io::{BufWriter, Write};

use mpi::topology::Communicator;
use mpi::collective::CommunicatorCollectives;
use rayon::ThreadPoolBuilder;
use ndarray::Array1;

use noci_rs::input::Input;
use noci_rs::AoData;
use noci_rs::SCFState;
use noci_rs::nonorthogonalwicks::{WicksShared, WicksView};
use noci_rs::noci::{NOCIData, MOCache};
use noci_rs::timers;
use noci_rs::time_call;

use noci_rs::input::load_input;
use noci_rs::read::read_integrals;
use noci_rs::basis::{generate_reference_noci_basis, generate_excited_basis};
use noci_rs::noci::{build_noci_hs, calculate_noci_energy, build_wicks_shared, build_mo_cache};
use noci_rs::deterministic::{propagate, projected_energy};
use noci_rs::stochastic::{qmc_step};
use noci_rs::snoci::{snoci_step};
use noci_rs::utils::{wavefunction_sparsity};
use noci_rs::mpiutils::{broadcast};
use noci_rs::write::{print_input};

/// Printed results for a given geometry.
struct Results {
    /// Geometry parameter for this calculation.
    r: f64,
    /// SCF states generated for this geometry.
    states: Vec<SCFState>,
    /// RHF energy at this geometry.
    e_rhf: f64,
    /// Reference-space NOCI energy at this geometry.
    e_noci_ref: f64,
    /// Deterministic NOCI-QMC energy if calculated.
    e_noci_qmc_det: Option<f64>,
    /// Stochastic NOCI-QMC energy if calculated.
    e_noci_qmc_stoch: Option<f64>,
    /// Selected NOCI energy if calculated.
    e_snoci: Option<f64>,
    /// FCI energy if available.
    e_fci: Option<f64>,
    /// Number of MPI ranks for printing.
    nranks: usize,
    /// Timings associated with this geometry.
    timings: timers::Totals,
}

type Atoms = Vec<String>;

/// Main.
fn main() {
    ThreadPoolBuilder::new().stack_size(128 * 1024 * 1024).build_global().unwrap();

    let t_total = Instant::now();
    let input_path = match std::env::args().nth(1) {
        Some(p) => p,
        None => {
            eprintln!("Usage: cargo run <input.lua>");
            std::process::exit(1);
        }
    };
    let mut input = load_input(&input_path);

    let mut prev_states: Vec<SCFState> = Vec::new();
    
    let universe = mpi::initialize().unwrap();
    let world = universe.world(); 
    let irank = world.rank();

    if irank == 0 {print_input(&input);}
    world.barrier();

    let rlist = input.mol.r_list.clone();
    let geoms = input.mol.geoms.clone();

    for (i, r) in rlist.iter().copied().enumerate() {
        println!("\n");
        let atoms: &Atoms = &geoms[i];
        let res = run(r, atoms, &mut input, &prev_states, &world);  
        if irank == 0 {print_report(&res, &input);}
        prev_states = res.states.clone();
    }
    if irank == 0 {println!("\n Total wall time: {:?}", t_total.elapsed());}
}

/// Wrapper fuction to call each required or requested type of calculation. Ordering is: 1)
/// Generate integrals in PySCF, run SCF for requested states, run the reference NOCI calculation,
/// and finally run the deterministic propagation NOCI-QMC calculation.
/// # Arguments:
/// - `r`: Current geometry.
/// - `atoms`: Atom types.
/// - `input`: User input specifications.
/// - `prev_states`: Converged SCF states at previous r, used for seeding.
/// - `world`: MPI communicator object.
/// # Returns
/// - `Results`: Calculated energies, timings, and SCF states for the current geometry.
fn run(r: f64, atoms: &Atoms, input: &mut Input, prev_states: &[SCFState], world: &impl Communicator) -> Results {
    
    let tol = 1e-8;
    let irank = world.rank();
    timers::reset_all();
    
    // Initialise timings struct and call PySCF.
    if irank == 0 {
        run_pyscf(atoms, input);
    }
    world.barrier();
    
    // Read in data generated by PySCF on all ranks.
    let ao: AoData = read_integrals("data.h5");

    // Create the following on all ranks such that they may be filled by broadcast.
    let mut states: Vec<SCFState> = Vec::new();
    let mut noci_reference_basis: Vec<SCFState> = Vec::new();
    let mut c0: Vec<f64> = Vec::new();
    let mut e_noci_ref: f64 = 0.0;
    let mut e_noci_qmc_det: Option<f64> = None;
    let mut e_noci_qmc_stoch: Option<f64> = None;
    let mut e_snoci: Option<f64> = None;
    
    // Run all non MPI parts of the code on rank 0. The deterministic propagation still uses Rayon
    // for multithreading. SCF calculations are currently single threaded. 
    if irank == 0 {
        // Run SCF calculations.
        let st = run_scf(&ao, input, prev_states);
        states = st;

        noci_reference_basis = states.iter().filter(|s| s.noci_basis).cloned().collect();
        for (i, st) in noci_reference_basis.iter_mut().enumerate() {
            st.parent = i;
        }
    }

    world.barrier();
    broadcast(world, &mut states);
    broadcast(world, &mut noci_reference_basis);

    // Construct intermediates for extended non-orthogonal Wick's theorem if using. The actual
    // computation happens on only world rank 0 (with rayon). If multiple shared memory regions are 
    // used multiple copies of the intermediates will be computed.
    let mut wicks_shared: Option<WicksShared> = time_call!(crate::timers::general::add_build_wicks_shared, {
        if input.wicks.enabled || input.wicks.compare {
            if irank == 0 {
                println!("{}", "=".repeat(100));
                println!("Precomputing Wick's intermediates....");
            }
            Some(build_wicks_shared(world, &ao, &noci_reference_basis, tol, input))
        } else {
            None
        }
    });

    // Transform all references used in NOCI basis to MO basis. This allows for evaluation of
    // matrix elements using standard Slater-Condon rules if the determinant pair share a parent.
    println!("Constructing reference NOCI MO basis....");
    let mocache = build_mo_cache(&ao, &noci_reference_basis);

    // Reference NOCI, deterministic propagation and selected NOCI (SNOCI) occur only on rank 0 (with Rayon).
    if irank == 0 {
        let wicks_view = wicks_shared.as_ref().map(|ws| ws.view());
        let (refb, e_ref, c0v) = run_reference_noci(&ao, input, &states, tol, &mocache, wicks_view);
        noci_reference_basis = refb;
        e_noci_ref = e_ref;
        c0 = c0v;

        if input.det.is_some() {
            let e_det = run_qmc_deterministic_noci(&ao, input, &states, &noci_reference_basis, &c0, &mocache, tol, wicks_view);
            e_noci_qmc_det = Some(e_det);
        }

        if input.snoci.is_some() {
            let e_snoci_res = run_snoci(&ao, &noci_reference_basis, &noci_reference_basis, input, tol, wicks_shared.as_mut(), &mocache);
            e_snoci = Some(e_snoci_res);
        }
    }

    world.barrier();
    broadcast(world, &mut noci_reference_basis);
    broadcast(world, &mut c0);
    broadcast(world, &mut e_noci_ref);

    // Run stochastic NOCI-QMC calculation across all MPI ranks.
    if input.qmc.is_some() {
        let wicks_view = wicks_shared.as_ref().map(|ws| ws.view());
        let e_qmc = run_qmc_stochastic_noci(&ao, input, &noci_reference_basis, &c0, world, tol, wicks_view, &mocache);
        e_noci_qmc_stoch = Some(e_qmc);
    }

    let timings = noci_rs::timers::snapshot_all_mpi(world); 
    Results {r, e_rhf: states[0].e, e_noci_ref, e_noci_qmc_det, e_noci_qmc_stoch, e_snoci, e_fci: ao.e_fci, timings, nranks: world.size() as usize, states: states.clone()}
}

/// Call PySCF script to get the two electron integrals and core hamiltonian.
/// # Arguments: 
/// - `atoms`: Atom types.
/// - `input`: User input specifications.
/// # Returns
/// - `()`: Runs the PySCF interface and writes the generated integrals to disk.
fn run_pyscf(atoms: &Atoms, input: &Input) {
    time_call!(crate::timers::general::add_run_pyscf, {
        let atomsj = serde_json::to_string(atoms).unwrap();
        
        // Call PySCF script via command line.
        let status = Command::new("python3").arg("generate.py").arg("--atoms").arg(&atomsj).arg("--basis").arg(&input.mol.basis)
                                            .arg("--unit").arg(&input.mol.unit).arg("--out").arg("data.h5").arg("--fci")
                                            .arg(if input.scf.do_fci { "true" } else { "false" }).status().unwrap();

        if !status.success() {
            eprintln!("Failed to generate mol with status {status}");
            std::process::exit(1);
        }
    })
}

/// Run SCF calculations for user requested SCF states.
/// # Arguments:
/// - `ao`: Contains AO integrals and other system data.
/// - `input`: User input specifications.
/// - `prev_states`: Converged SCF states at previous r, used for seeding. 
/// # Returns
/// - `Vec<SCFState>`: Converged SCF states.
fn run_scf(ao: &AoData, input: &mut Input, prev_states: &[SCFState]) -> Vec<SCFState> {
    time_call!(crate::timers::general::add_run_scf, {
        if prev_states.is_empty() {
            generate_reference_noci_basis(ao, input, None)
        } else {
            generate_reference_noci_basis(ao, input, Some(prev_states))
        }
    })
}

/// Construct the reference NOCI basis and find the reference NOCI energy via calculation of NOCI
/// Hamiltonian and overlap followed by solving GEVP.
/// # Arguments:
/// - `ao`: Contains AO integrals and other system data.
/// - `input`: User input specifications.
/// - `states`: Converged SCF states.
/// - `tol`: Tolerance up to which a number is considered zero.
/// - `mocache`: MO-basis one and two-electron integral caches.
/// - `wicks`: Optional precomputed Wick's intermediates.
/// # Returns
/// - `(Vec<SCFState>, f64, Vec<f64>)`: Reference NOCI basis, reference NOCI energy, and reference NOCI coefficients.
fn run_reference_noci(ao: &AoData, input: &Input, states: &[SCFState], tol: f64, mocache: &[MOCache], wicks: Option<&WicksView>) -> (Vec<SCFState>, f64, Vec<f64>) {
    time_call!(crate::timers::general::add_run_reference_noci, {
        let mut noci_reference_basis: Vec<SCFState> = states.iter().filter(|s| s.noci_basis).cloned().collect();
        for (i, st) in noci_reference_basis.iter_mut().enumerate() {
            st.parent = i;
        }

        let (e_noci_ref, c0, _) = time_call!(crate::timers::general::add_calculate_noci_energy, {
            calculate_noci_energy(ao, input, &noci_reference_basis, tol, mocache, wicks)
        });

        (noci_reference_basis, e_noci_ref, c0.to_vec())
    })
}

/// Perform the deterministic propagation in the NOCI-QMC space. 
/// # Arguments:
/// - `ao`: Contains AO integrals and other system data.
/// - `input`: User input specifications.
/// - `states`: Converged SCF states. 
/// - `noci_reference_basis`: The converged SCF states filtered for those requested
///   to be in the NOCI basis.
/// - `c0`: Initial coefficient vector of basis states.
/// - `tol`: Tolerance up to which a number is considered zero.
/// - `mocache`: MO-basis one and two-electron integral caches.
/// - `wicks`: Optional precomputed Wick's intermediates.
/// # Returns
/// - `f64`: Propagated energy.
fn run_qmc_deterministic_noci(ao: &AoData, input: &Input, states: &[SCFState], noci_reference_basis: &[SCFState], c0: &[f64], mocache: &[MOCache],
                              tol: f64, wicks: Option<&WicksView>) -> f64 {
    time_call!(crate::timers::deterministic::add_run_qmc_deterministic_noci, {
        println!("{}", "=".repeat(100));
        println!("Building NOCI-QMC basis....");

        let include_refs = true;
        let basis = time_call!(crate::timers::deterministic::add_generate_excited_basis, {
            generate_excited_basis(noci_reference_basis, input, include_refs)
        });

        let n = basis.len();
        println!("Built NOCI-QMC basis of {} determinants.", n);
        println!("Calculating NOCI-QMC deterministic propagation matrix elements for {} determinants ({} elements)...", n, n * n);

        let symmetric = true;
        let data = NOCIData::new(ao, &basis, input, tol, wicks).withmocache(mocache);
        let (h, s, _) = time_call!(crate::timers::deterministic::add_build_noci_hs, {
            build_noci_hs(&data, &basis, &basis, symmetric)
        });
        println!("Finished calculating NOCI-QMC matrix elements.");

        let es = states[0].e;
        println!("Running deterministic NOCI-QMC propagation....");

        let mut c0qmc = Array1::<f64>::zeros(n);
        if !input.write.write_deterministic_coeffs {
            for (i, ref_st) in noci_reference_basis.iter().enumerate() {
                let idx = basis.iter().position(|qmc_st| qmc_st.label == ref_st.label).unwrap();
                c0qmc[idx] = c0[i];
            }
        } else {
            c0qmc = Array1::from_elem(n, 1.0 / (n as f64).sqrt());
        };

        println!("Initial wavefunction ansatz (C0-QMC): {}", c0qmc);

        let ref_indices: Vec<usize> = noci_reference_basis.iter().map(|ref_st| {basis.iter()
                                      .position(|qmc_st| qmc_st.label == ref_st.label).unwrap()}).collect();

        let mut coefficients = Vec::new();

        let c = time_call!(crate::timers::deterministic::add_propagate, {
            propagate(&h, &s, &c0qmc, es, &mut coefficients, input)
        });

        let cfinal = match c {
            Some(c) => c,
            None => {
                println!("Propagation failed.");
                std::process::exit(1);
            }
        };

        let e = projected_energy(&h, &s, &cfinal);
        wavefunction_sparsity(cfinal.as_slice().unwrap(), &ref_indices);

        if input.write.write_deterministic_coeffs {
            println!("Writing coefficients to file...");
            let filepath = format!("{}/{}", input.write.write_dir, "coefficients");
            let file = File::create(filepath).unwrap();
            let mut writer = BufWriter::new(file);
            for iter in &coefficients {
                writeln!(writer, "iter {}", iter.iter).unwrap();
                writeln!(writer, "Full coefficients:").unwrap();
                for (i, z) in iter.c_full.iter().enumerate() {
                    writeln!(writer, "{:4} {:.8e}", i, z).unwrap();
                }
                writeln!(writer, "Relevant space coefficients:").unwrap();
                for (i, z) in iter.c_relevant.iter().enumerate() {
                    writeln!(writer, "{:4} {:.8e}", i, z).unwrap();
                }
                writeln!(writer, "Null space coefficients:").unwrap();
                for (i, z) in iter.c_null.iter().enumerate() {
                    writeln!(writer, "{:4} {:.8e}", i, z).unwrap();
                }
                writeln!(writer).unwrap();
            }
        }

        e
    })
}

/// Perform stochastic propagation in the NOCI-QMC space. 
/// # Arguments:
/// - `ao`: Contains AO integrals and other system data.
/// - `input`: User input specifications.
/// - `noci_reference_basis`: The converged SCF states filtered for those requested
///   to be in the NOCI basis.
/// - `c0`: Initial coefficient vector of basis states.
/// - `world`: MPI communicator object (MPI_COMM_WORLD).
/// - `tol`: Tolerance up to which a number is considered zero.
/// - `wicks`: Optional precomputed Wick's intermediates.
/// - `mocache`: MO-basis one and two-electron integral caches.
/// # Returns
/// - `f64`: Stochastic energy estimate.
pub fn run_qmc_stochastic_noci(ao: &AoData, input: &mut Input, noci_reference_basis: &[SCFState], c0: &[f64], world: &impl Communicator, tol: f64,
                               wicks: Option<&WicksView>, mocache: &[MOCache]) -> f64 {
    time_call!(crate::timers::stochastic::add_run_qmc_stochastic_noci, {
        let irank = world.rank();

        if irank == 0 {
            println!("{}", "=".repeat(100));
            println!("Building NOCI-QMC basis....");
        }

        let include_refs = true;
        let basis = time_call!(crate::timers::stochastic::add_generate_excited_basis, {
            generate_excited_basis(noci_reference_basis, input, include_refs)
        });
        let n = basis.len();

        let ref_indices: Vec<usize> = noci_reference_basis.iter().map(|ref_st| {basis.iter()
                                      .position(|qmc_st| qmc_st.label == ref_st.label).unwrap()}).collect();

        let mut c0qmc = vec![0.0_f64; n];
        for (i, ref_st) in noci_reference_basis.iter().enumerate() {
            let idx = basis.iter().position(|qmc_st| qmc_st.label == ref_st.label).unwrap();
            c0qmc[idx] = c0[i];
        }

        if irank == 0 {
            println!("Built NOCI-QMC basis of {} determinants.", n);
            println!("Running stochastic NOCI-QMC propagation....");
        }

        let mut es = basis[0].e;
        let data = NOCIData::new(ao, &basis, input, tol, wicks).withmocache(mocache);
        let (e, local_hist) = time_call!(crate::timers::stochastic::add_qmc_step, {
            qmc_step(&data, &c0qmc, &mut es, &ref_indices, world)
        });

        if let Some(hist) = local_hist.as_ref() && input.write.write_excitation_hist {
            if irank == 0 {println!("Writing excitation samples to file...");}
            let filepath = format!("{}/excitationsamples{}", input.write.write_dir, irank);
            let file = File::create(filepath).unwrap();
            let mut writer = BufWriter::new(file);

            writeln!(writer, "{} {} {}", hist.logmin, hist.logmax, hist.nbins).unwrap();
            writeln!(writer, "{} {} {}", hist.ntotal, hist.noverflow_low, hist.noverflow_high).unwrap();

            for &c in &hist.counts {
                writeln!(writer, "{}", c).unwrap();
            }
        }

        e
    })
}

/// Run SNOCI starting from the current determinant space.
/// # Arguments:
/// - `ao`: Contains AO integrals and other system data.
/// - `initial_space`: Current determinant space used as the starting point for SNOCI.
/// - `noci_reference_basis`: Vector of only the reference determinants.
/// - `input`: User input specifications.
/// - `tol`: Tolerance up to which a number is considered zero.
/// - `wicks`: Optional shared-memory Wick's intermediates storage.
/// - `mocache`: MO-basis one and two-electron integral caches.
/// # Returns
/// - `f64`: Current SNOCI energy.
pub fn run_snoci(ao: &AoData, initial_space: &[SCFState], noci_reference_basis: &[SCFState], input: &Input, tol: f64,
                 wicks: Option<&mut WicksShared>, mocache: &[MOCache]) -> f64 {
    time_call!(crate::timers::snoci::add_run_snoci, {
        let current_space = initial_space.to_vec();
        let state = snoci_step(ao, &current_space, noci_reference_basis, input, mocache, tol, wicks);
        state.ecurrent
    })
}

/// Print important information for current geometry.
/// # Arguments:
/// - `res`: Contains the aforementioned important information.
/// - `input`: User input specifications.
/// # Returns
/// - `()`: Prints the report to stdout.
fn print_report(res: &Results, input: &Input) {

    fn print_counter(lbl: &str, c: noci_rs::timers::Counter, indent: usize) {
        let avg = if c.calls > 0 {std::time::Duration::from_nanos(c.ns / c.calls)} else {std::time::Duration::from_nanos(0)};
        println!("{}{}: {:?} [{} calls, avg {:?}/call]", " ".repeat(indent), lbl, c.duration(), c.calls, avg);
    }

    fn print_thread_counter(lbl: &str, c: noci_rs::timers::Counter, wall: noci_rs::timers::Counter, nthreads: usize, indent: usize) {
        let avg = if c.calls > 0 {std::time::Duration::from_nanos(c.ns / c.calls)} else {std::time::Duration::from_nanos(0)};
        let pad = " ".repeat(indent);
        if wall.ns == 0 || nthreads == 0 {
            println!("{}{}: {:?} [{} calls, avg {:?}/call, thread time]", pad, lbl, c.duration(), c.calls, avg);
            return;
        }

        let active = c.ns as f64 / wall.ns as f64;
        let eff = 100.0 * active / nthreads as f64;
        println!("{}{}: {:?} [{} calls, avg {:?}/call, thread time, avg active threads {:.2}/{}, efficiency {:.1}%]",
                 pad, lbl, c.duration(), c.calls, avg, active, nthreads, eff);
    }

    let nthreads = rayon::current_num_threads();

    let hs_wall = noci_rs::timers::Counter {
        ns: res.timings.general.calculate_noci_energy.ns
          + res.timings.deterministic.build_noci_hs.ns
          + res.timings.stochastic.step.propagate_iteration.ns
          + res.timings.snoci.solve_current_space.ns
          + res.timings.snoci.build_candidate_h_ai.ns,
        calls: 0,
    };

    let wick_wall = noci_rs::timers::Counter {
        ns: hs_wall.ns
          + res.timings.snoci.candidate_pool_new.ns
          + res.timings.snoci.candidate_pool_update.ns
          + res.timings.snoci.candidate_pool_filter_candidates.ns,
        calls: 0,
    };

    println!("{}", "=".repeat(100));
    println!("Number of MPI ranks: {}", res.nranks);
    println!("Number of Rayon threads per rank: {}", nthreads);
    println!("Warning: Timing functions will impact performance and thread efficiency.");
    println!("Please interpret these timings as a distribution but not absolute.");
    println!("Timing overhead will be quite large relative to some of the smaller kernels.");
    println!();

    print_counter("Total PySCF time", res.timings.general.run_pyscf, 0);
    print_counter("Total SCF time", res.timings.general.run_scf, 0);
    print_counter("Total Reference NOCI time", res.timings.general.run_reference_noci, 0);
    print_counter(r"S & H_1 & H_2", res.timings.general.calculate_noci_energy, 1);
    print_counter("Wick's Intermediates Construction time", res.timings.general.build_wicks_shared, 0);
    println!();

    if input.det.is_some() {
        print_counter("Total NOCI-QMC deterministic time", res.timings.deterministic.run_qmc_deterministic_noci, 0);
        print_counter("Basis generation", res.timings.deterministic.generate_excited_basis, 2);
        print_counter(r"S & H_1 & H_2", res.timings.deterministic.build_noci_hs, 2);
        print_counter("Deterministic propagation", res.timings.deterministic.propagate, 2);
        println!();
    }
    
    if input.qmc.is_some() {
        print_counter("Total NOCI-QMC stochastic time", res.timings.stochastic.run_qmc_stochastic_noci, 0);
        print_counter("Basis generation", res.timings.stochastic.generate_excited_basis, 2);
        print_counter("Stochastic propagation", res.timings.stochastic.qmc_step, 2);
        print_counter("Walker initialisation", res.timings.stochastic.step.initialise_walkers, 5);
        print_counter("Spawning, Death and Cloning", res.timings.stochastic.step.propagate_iteration, 5);
        print_counter("Accumulate updates and pack MPI buffers", res.timings.stochastic.step.acc_pack_updates, 5);
        print_counter("Communicate spawn updates MPI", res.timings.stochastic.step.communicate_spawn_updates, 5);
        print_counter("Unpack updates and accumulate", res.timings.stochastic.step.unpack_received_updates, 5);
        print_counter("Apply population updates", res.timings.stochastic.step.apply_delta, 5);
        print_counter("Update pG", res.timings.stochastic.step.update_p, 5);
        print_counter("Update pG count gather", res.timings.stochastic.step.update_p_gather_counts, 8);
        print_counter("Update pG local overlapping", res.timings.stochastic.step.update_p_local_overlap, 8);
        print_counter("Update pG wait for remote updates", res.timings.stochastic.step.update_p_wait, 8);
        print_counter("Update pG apply remote updates", res.timings.stochastic.step.update_p_apply, 8);
        print_counter("Calculate projected energy", res.timings.stochastic.step.update_projected_energy, 5);
        print_counter("Compute populations", res.timings.stochastic.step.compute_populations, 5);
        print_counter("Observables all-reduce", res.timings.stochastic.step.observables_allreduce, 8);
        println!();
    }

    if input.snoci.is_some() {
        print_counter("Total SNOCI time", res.timings.snoci.run_snoci, 0);
        print_counter("Full SNOCI step", res.timings.snoci.snoci_step, 2);
        print_counter("Current space H, S and GEVP", res.timings.snoci.solve_current_space, 2);
        print_counter("Initial candidate pool generation", res.timings.snoci.candidate_pool_new, 2);
        print_counter("Update candidate pool overlaps", res.timings.snoci.candidate_pool_update, 2);
        print_counter("Filter candidate pool", res.timings.snoci.candidate_pool_filter_candidates, 2);
        print_counter("Pseudoinverse", res.timings.snoci.build_pseudoinverse, 2);
        print_counter("Build Omega space S", res.timings.snoci.project_candidate_space, 2);
        print_counter("Candidate-current space H", res.timings.snoci.build_candidate_h_ai, 2);
        print_counter("Generalised Fock build", res.timings.snoci.build_generalised_fock, 2);
        print_counter("Fock MOs", res.timings.snoci.build_fock_mo_cache, 2);
        print_counter("Update Wick Fock intermediates", res.timings.snoci.update_wicks_fock, 2);
        print_counter("Candidate space Fock", res.timings.snoci.build_focks, 2);
        print_counter("Build Omega space F and V", res.timings.snoci.build_omega_fock, 2);
        print_counter("GMRES Solve", res.timings.snoci.gmres, 2);
        print_counter("Candidate selection", res.timings.snoci.select_candidates, 2);
        println!();
    }
    
    println!("Shared matrix-element timings");
    print_thread_counter("Hamiltonian and overlap dispatch", res.timings.noci.calculate_hs_pair, hs_wall, nthreads, 2);
    print_thread_counter("Hamiltonian and overlap via Wick's theorem", res.timings.noci.calculate_hs_pair_wicks, hs_wall, nthreads, 2);
    print_thread_counter("Hamiltonian and overlap via generalised Slater-Condon", res.timings.noci.calculate_hs_pair_naive, hs_wall, nthreads, 2);
    print_thread_counter("Hamiltonian and overlap via orthogonal Slater-Condon", res.timings.noci.calculate_hs_pair_orthogonal, hs_wall, nthreads, 2);
    println!();
    
    println!("Shared nonorthogonal Wick timings");
    print_thread_counter("Prepare same-spin information", res.timings.nonorthogonalwicks.prepare_same, wick_wall, nthreads, 2);
    print_thread_counter("Prepare same-spin information (generic)", res.timings.nonorthogonalwicks.prepare_same_gen, wick_wall, nthreads, 5);
    print_thread_counter("Prepare same-spin information (m = 0)", res.timings.nonorthogonalwicks.prepare_same_m0, wick_wall, nthreads, 5);
    print_thread_counter("Prepare same-spin information (m = 0, l = 1)", res.timings.nonorthogonalwicks.prepare_same_m0_l1, wick_wall, nthreads, 8);
    print_thread_counter("Prepare same-spin information (m = 0, l = 2)", res.timings.nonorthogonalwicks.prepare_same_m0_l2, wick_wall, nthreads, 8);
    print_thread_counter("Same-spin mix determinants and adjugates", res.timings.nonorthogonalwicks.get_det_adjt_same, wick_wall, nthreads, 2);
    print_thread_counter("Different-spin mix determinants and adjugates", res.timings.nonorthogonalwicks.get_det_adjt_diff, wick_wall, nthreads, 2);
    print_thread_counter("Construct determinant indices", res.timings.nonorthogonalwicks.construct_determinant_indices, wick_wall, nthreads, 2);
    print_thread_counter("Overlap matrix elements", res.timings.nonorthogonalwicks.lg_overlap, wick_wall, nthreads, 2);
    print_thread_counter("One-electron matrix elements", res.timings.nonorthogonalwicks.lg_h1, wick_wall, nthreads, 2);
    print_thread_counter("One-electron matrix elements (generic)", res.timings.nonorthogonalwicks.lg_one_body_gen, wick_wall, nthreads, 5);
    print_thread_counter("One-electron matrix elements (m = 0)", res.timings.nonorthogonalwicks.lg_one_body_m0, wick_wall, nthreads, 5);
    print_thread_counter("One-electron matrix elements (m = 0, generic)", res.timings.nonorthogonalwicks.lg_one_body_m0_gen, wick_wall, nthreads, 8);
    print_thread_counter("One-electron matrix elements (m = 0, l = 1)", res.timings.nonorthogonalwicks.lg_one_body_m0_l1, wick_wall, nthreads, 8);
    print_thread_counter("One-electron matrix elements (m = 0, l = 2)", res.timings.nonorthogonalwicks.lg_one_body_m0_l2, wick_wall, nthreads, 8);
    print_thread_counter("Same-spin two-electron matrix elements", res.timings.nonorthogonalwicks.lg_h2_same, wick_wall, nthreads, 2);
    print_thread_counter("Same-spin two-electron matrix elements (generic)", res.timings.nonorthogonalwicks.lg_h2_same_gen, wick_wall, nthreads, 5);
    print_thread_counter("Same-spin two-electron matrix elements (m = 0)", res.timings.nonorthogonalwicks.lg_h2_same_m0, wick_wall, nthreads, 5);
    print_thread_counter("Same-spin two-electron matrix elements (m = 0, generic)", res.timings.nonorthogonalwicks.lg_h2_same_m0_gen, wick_wall, nthreads, 8);
    print_thread_counter("Same-spin two-electron matrix elements (m = 0, l = 1)", res.timings.nonorthogonalwicks.lg_h2_same_m0_l1, wick_wall, nthreads, 8);
    print_thread_counter("Same-spin two-electron matrix elements (m = 0, l = 2)", res.timings.nonorthogonalwicks.lg_h2_same_m0_l2, wick_wall, nthreads, 8);
    print_thread_counter("Same-spin two-electron matrix elements (m = 0, l = 3)", res.timings.nonorthogonalwicks.lg_h2_same_m0_l3, wick_wall, nthreads, 8);
    print_thread_counter("Different-spin two-electron matrix elements", res.timings.nonorthogonalwicks.lg_h2_diff, wick_wall, nthreads, 2);
    print_thread_counter("Different-spin two-electron matrix elements (generic)", res.timings.nonorthogonalwicks.lg_h2_diff_gen, wick_wall, nthreads, 5);
    print_thread_counter("Different-spin two-electron matrix elements (m = 0)", res.timings.nonorthogonalwicks.lg_h2_diff_m0, wick_wall, nthreads, 5);
    print_thread_counter("Different-spin two-electron matrix elements (m = 0, generic)", res.timings.nonorthogonalwicks.lg_h2_diff_m0_gen, wick_wall, nthreads, 8);
    print_thread_counter("Different-spin two-electron matrix elements (m = 0, la = 1, lb = 1)", res.timings.nonorthogonalwicks.lg_h2_diff_m0_11, wick_wall, nthreads, 8);
    print_thread_counter("Different-spin two-electron matrix elements (m = 0, la = 1, lb = 3)", res.timings.nonorthogonalwicks.lg_h2_diff_m0_13, wick_wall, nthreads, 8);
    print_thread_counter("Different-spin two-electron matrix elements (m = 0, la = 2, lb = 2)", res.timings.nonorthogonalwicks.lg_h2_diff_m0_22, wick_wall, nthreads, 8);
    print_thread_counter("Different-spin two-electron matrix elements (m = 0, la = 3, lb = 1)", res.timings.nonorthogonalwicks.lg_h2_diff_m0_31, wick_wall, nthreads, 8);
    println!();

    println!("R: {}", res.r);
    for (i, st) in res.states.iter().enumerate() {
        println!("State({}): {},  E: {}", i + 1, st.label, st.e);
    }

    println!("State(NOCI-reference): E: {}, [E - E(RHF)]: {}", res.e_noci_ref, res.e_noci_ref - res.e_rhf);
    if let Some(e_det) = res.e_noci_qmc_det {println!("State(NOCI-qmc-deterministic): E: {}, [E - E(RHF)]: {}", e_det, e_det - res.e_rhf);}
    if res.e_noci_qmc_stoch.is_some() {println!("State(NOCI-qmc-qmc): Blocking analysis must be performed");}
    if let Some(e_snoci) = res.e_snoci {println!("State(SNOCI): E: {}, [E - E(RHF)]: {}", e_snoci, e_snoci - res.e_rhf);}
    if let Some(e_fci) = res.e_fci {println!("State(FCI): E: {},  [E - E(RHF)]: {}", e_fci, e_fci - res.e_rhf);}

    println!("{}", "=".repeat(100));
}
