// main.rs 
use std::process::Command;
use std::time::{Instant, Duration};
use std::default::Default;
use std::fs::File;
use std::io::{BufWriter, Write};

use mpi::topology::Communicator;
use mpi::collective::CommunicatorCollectives;
use ndarray::Array1;

use noci_rs::input::Input;
use noci_rs::AoData;
use noci_rs::SCFState;
use noci_rs::nonorthogonalwicks::{WicksShared, WicksView};
use noci_rs::stochastic::StochStepTimings;

use noci_rs::input::load_input;
use noci_rs::read::read_integrals;
use noci_rs::basis::{generate_reference_noci_basis, generate_qmc_noci_basis};
use noci_rs::noci::{build_noci_matrices, calculate_noci_energy, build_wicks_shared};
use noci_rs::deterministic::{propagate, projected_energy};
use noci_rs::stochastic::{step};
use noci_rs::utils::{wavefunction_sparsity};
use noci_rs::mpiutils::{broadcast};

// Timing storage for various segements of code.
#[derive(Default)]
struct Timings {
    pyscf: Duration,
    scf: Duration,
    noci_ref_total: Duration,
    noci_ref_hs: Duration,
    wicks_intermediates: Duration,
    // Deterministic timings.
    qmc_det_total: Duration,
    qmc_det_basis: Duration,
    qmc_det_hs: Duration,
    qmc_det_prop: Duration,
    // Stochastic timings. No timing for forming Hamiltonian as we do not do this in true QMC.
    qmc_stoch_total: Duration,
    qmc_stoch_basis: Duration,
    qmc_stoch_prop: Duration,
    qmc_stoch_step: StochStepTimings,
}

// Printed results for a given geometry.
struct Results {
    r: f64,
    states: Vec<SCFState>,
    e_rhf: f64,
    e_noci_ref: f64,
    e_noci_qmc_det: Option<f64>,
    e_noci_qmc_stoch: Option<f64>,
    e_fci: Option<f64>,
    timings: Timings,
}

type Atoms = Vec<String>;

/// Main.
fn main() {
    let t_total = Instant::now();
    let input_path = match std::env::args().nth(1) {
        Some(p) => p,
        None => {
            eprintln!("Usage: cargo run <input.lua>");
            std::process::exit(1);
        }
    };
    let mut input = load_input(&input_path);

    let mut prev_states: Vec<SCFState> = Vec::new();
    
    let universe = mpi::initialize().unwrap();
    let world = universe.world(); 
    let irank = world.rank();

    let rlist = input.mol.r_list.clone();
    let geoms = input.mol.geoms.clone();

    for (i, r) in rlist.iter().copied().enumerate() {
        println!("\n");
        let atoms: &Atoms = &geoms[i];
        let res = run(r, atoms, &mut input, &prev_states, &world);  
        if irank == 0 {print_report(&res, &input);}
        prev_states = res.states.clone();
    }
    if irank == 0 {println!("\n Total wall time: {:?}", t_total.elapsed());}
}

/// Wrapper fuction to call each required or requested type of calculation. Ordering is: 1)
/// Generate integrals in PySCF, run SCF for requested states, run the reference NOCI calculation,
/// and finally run the deterministic propagation NOCI-QMC calculation.
/// # Arguments:
///     `r`: f64, current geometry.
///     `atoms`: Vec<String>, atom types.
///     `prev_states`: [SCFState], converged SCF states at previous r, used for seeding.
fn run(r: f64, atoms: &Atoms, input: &mut Input, prev_states: &[SCFState], world: &impl Communicator) -> Results {
    
    let tol = 1e-8;
    let irank = world.rank();
    let mut timings = Timings::default();
    
    // Initialise timings struct and call PySCF.
    if irank == 0 {timings.pyscf = run_pyscf(atoms, input);}
    world.barrier();
    
    // Read in data generated by PySCF on all ranks.
    let ao: AoData = read_integrals("data.h5");

    // Create the following on all ranks such that they may be filled by broadcast.
    let mut states: Vec<SCFState> = Vec::new();
    let mut noci_reference_basis: Vec<SCFState> = Vec::new();
    let mut c0: Vec<f64> = Vec::new();
    let mut e_noci_ref: f64 = 0.0;
    let mut e_noci_qmc_det: Option<f64> = None;
    let mut e_noci_qmc_stoch: Option<f64> = None;
    
    // Run all non MPI parts of the code on rank 0. The deterministic propagation still uses Rayon
    // for multithreading. SCF calculations are currently single threaded. 
    if irank == 0 {
        // Run SCF calculations.
        let (st, d_scf) = run_scf(&ao, input, prev_states);
        states = st;
        timings.scf = d_scf;

        noci_reference_basis = states.iter().filter(|s| s.noci_basis).cloned().collect();
        for (i, st) in noci_reference_basis.iter_mut().enumerate() {
            st.parent = i;
        }
    }

    world.barrier();
    broadcast(world, &mut states);
    broadcast(world, &mut noci_reference_basis);
    
    // Construct intermediates for extended non-orthogonal Wick's theorem if using. The actual
    // computation happens on only rank 0 (with rayon).
    let t_wi = Instant::now();
    let mut wicks_shared: Option<WicksShared> = None;
    if input.wicks.enabled || input.wicks.compare {
        if irank == 0 {
            println!("{}", "=".repeat(100));
            println!("Precomputing Wick's intermediates....");
        }
        wicks_shared = Some(build_wicks_shared(world, &ao, &noci_reference_basis, tol));
    };
    let d_wi = t_wi.elapsed();
    let wicks_view: Option<&WicksView> = wicks_shared.as_ref().map(|ws| ws.view());

    // Deteministic propagation and reference NOCI happen only on rank 0 (with rayon).
    if irank == 0 {
        // Run NOCI reference calculation.
        let (refb, e_ref, c0v, d_tot, d_hs_ref) = run_reference_noci(&ao, input, &states, tol, wicks_view);
        // Note that noci_reference_basis and states above are the same if every requested basis
        // state in the input file has noci = true.
        noci_reference_basis = refb;
        e_noci_ref = e_ref;
        c0 = c0v;
        timings.noci_ref_total = d_tot;
        timings.noci_ref_hs = d_hs_ref;

        if input.det.is_some() {
            let (e_det, d_tot, d_basis, d_hs, d_prop) = run_qmc_deterministic_noci(&ao, input, &states, &noci_reference_basis, &c0, tol, wicks_view);
            e_noci_qmc_det = Some(e_det);
            timings.qmc_det_total = d_tot;
            timings.qmc_det_basis = d_basis;
            timings.qmc_det_hs = d_hs;
            timings.qmc_det_prop = d_prop;
            timings.wicks_intermediates = d_wi;
        }
    }

    world.barrier();
    broadcast(world, &mut noci_reference_basis);
    broadcast(world, &mut c0);
    broadcast(world, &mut e_noci_ref);
    
    // Run stochastic NOCI-QMC calculation across all MPI ranks.
    if input.qmc.is_some() {
        let (e_qmc, d_qmc_stoch_total, d_qmc_stoch_basis, d_qmc_stoch_prop, step_timings) = run_qmc_stochastic_noci(&ao, input, &noci_reference_basis, &c0, world, tol, wicks_view);
        e_noci_qmc_stoch = Some(e_qmc);
        timings.qmc_stoch_total = d_qmc_stoch_total;
        timings.qmc_stoch_basis = d_qmc_stoch_basis;
        timings.qmc_stoch_prop = d_qmc_stoch_prop;
        timings.qmc_stoch_step  = step_timings;
        timings.wicks_intermediates = d_wi;
    }
    Results {r, e_rhf: states[0].e, e_noci_ref, e_noci_qmc_det, e_noci_qmc_stoch, e_fci: ao.e_fci, timings, states: states.clone()}
}

/// Call PySCF script to get the two electron integrals and core hamiltonian.
/// # Arguments: 
///     `atoms`: Vec<String>, atom types.
///     `input`: Input, user input specifications.
fn run_pyscf(atoms: &Atoms, input: &Input) -> Duration {
    let t_gen = Instant::now();
    let atomsj = serde_json::to_string(atoms).unwrap();
    
    // Call PySCF script via command line.
    let status = Command::new("python3").arg("generate.py").arg("--atoms").arg(&atomsj).arg("--basis").arg(&input.mol.basis)
                                        .arg("--unit").arg(&input.mol.unit).arg("--out").arg("data.h5").arg("--fci")
                                        .arg(if input.scf.do_fci { "true" } else { "false" }).status().unwrap();

    if !status.success() {
        eprintln!("Failed to generate mol with status {status}");
        std::process::exit(1);
    }

    t_gen.elapsed()
}

/// Run SCF calculations for user requested SCF states.
/// # Arguments:
///     `ao`: AoData, contains AO integrals and other system data.
///     `input`: Input, user input specifications.
///     `prev_states`: [SCFState], converged SCF states at previous r, used for seeding. 
fn run_scf(ao: &AoData, input: &mut Input, prev_states: &[SCFState]) -> (Vec<SCFState>, Duration) {
    let t_scf = Instant::now();
    
    // Use the previous states to seed new SCF calculations if they exist.
    let states = if prev_states.is_empty() {
        generate_reference_noci_basis(ao, input, None)
    } else {
        generate_reference_noci_basis(ao, input, Some(prev_states))
    };

    (states, t_scf.elapsed())
}

/// Construct the reference NOCI basis and find the reference NOCI energy via calculation of NOCI
/// Hamiltonian and overlap followed by solving GEVP.
/// # Arguments:
///     `ao`: AoData, contains AO integrals and other system data.
///     `input`: Input, user input specifications.
///     `states`: [SCFState], converged SCF states. 
fn run_reference_noci(ao: &AoData, input: &Input, states: &[SCFState], tol: f64, wicks: Option<&WicksView>) 
                      -> (Vec<SCFState>, f64, Vec<f64>, Duration, Duration) {
    let t_noci = Instant::now();
    
    // Filter for the SCF states the user requested to be used in the NOCI basis.
    let mut noci_reference_basis: Vec<SCFState> = states.iter().filter(|s| s.noci_basis).cloned().collect();
    for (i, st) in noci_reference_basis.iter_mut().enumerate() {
        st.parent = i;
    }
    // Call matrix element and diagonalisation routines.
    let (e_noci_ref, c0, d_h_ref) = calculate_noci_energy(ao, input, &noci_reference_basis, tol, wicks);

    (noci_reference_basis, e_noci_ref, c0.to_vec(), t_noci.elapsed(), d_h_ref)
}

/// Perform the deterministic propagation in the NOCI-QMC space. 
/// # Arguments:
///     `ao`: AoData, contains AO integrals and other system data.
///     `input`: Input, user input specifications.
///     `states`: [SCFState], converged SCF states. 
///     `noci_reference_basis`: [SCFState], the converged SCF states filtered for those requested
///                             to be in the NOCI basis.
///     `c0`: [f64], initial coefficient vector of basis states.
fn run_qmc_deterministic_noci(ao: &AoData, input: &Input, states: &[SCFState], noci_reference_basis: &[SCFState], c0: &[f64], tol: f64, 
                              wicks: Option<&WicksView>) -> (f64, Duration, Duration, Duration, Duration) {
    let t_total = Instant::now();

    println!("{}", "=".repeat(100));
    println!("Building NOCI-QMC basis....");
    
    // Build excitations atop NOCI-reference basis.
    let t_basis = Instant::now();
    let basis = generate_qmc_noci_basis(noci_reference_basis, input);
    let d_basis = t_basis.elapsed();

    let n = basis.len();
    println!("Built NOCI-QMC basis of {} determinants.", n);
    println!("Calculating NOCI-QMC deterministic propagation matrix elements for {} determinants ({} elements)...", n, n * n);
    
    // Call matrix element routines.
    let (h, s, d_hs) = build_noci_matrices(ao, input, &basis, noci_reference_basis, tol, wicks);
    println!("Finished calculating NOCI-QMC matrix elements.");
    
    // Choose initial shift.
    let es = states[0].e; // RHF energy.
    println!("Running deterministic NOCI-QMC propagation....");

    // Embed reference NOCI coefficient vector in full NOCI-QMC space.
    let mut c0qmc = Array1::<f64>::zeros(n); 
    // If we are not interested in plotting evolution of individual coefficients we use the
    // reference NOCI coefficients as our initial guess as this is the best guess, however,
    // the coefficients often don't change much which makes for a boring plot.
    if !input.write.write_deterministic_coeffs {
        for (i, ref_st) in noci_reference_basis.iter().enumerate() {
            let idx = basis.iter().position(|qmc_st| qmc_st.label == ref_st.label).unwrap();
            c0qmc[idx] = c0[i];
        }
    // If we are interested in plotting the evolution of individual coefficients we use an
    // equal weighting of all SCF states as our initial guess.
    } else {
        c0qmc = Array1::from_elem(n, 1.0 / (n as f64).sqrt());
    }; 

    println!("Initial wavefunction ansatz (C0-QMC): {}", c0qmc);
    
    // Save indices in the coefficients vector of the references.
    let ref_indices: Vec<usize> = noci_reference_basis.iter().map(|ref_st| {basis.iter()
                                  .position(|qmc_st| qmc_st.label == ref_st.label).unwrap()}).collect();
    
    // Coefficient storage if we are writing.
    let mut coefficients = Vec::new();
    
    // Perform the propagation.
    let t_prop = Instant::now();
    let c = propagate(&h, &s, &c0qmc, es, &mut coefficients, input);
    let d_prop = t_prop.elapsed();

    let cfinal = match c {
        Some(c) => c,
        None => {
            println!("Propagation failed."); 
            std::process::exit(1);
        }
    };
    
    // Calculate energy and final diagnostics.
    let e = projected_energy(&h, &s, &cfinal);
    wavefunction_sparsity(cfinal.as_slice().unwrap(), &ref_indices);
    
    // Write projected coefficients to a file. This should currently only be used if doing a single 
    // geometry at a time otherwise the previous file will be overwritten.
    if input.write.write_deterministic_coeffs {
        println!("Writing coefficients to file...");
        let filepath = format!("{}/{}", input.write.write_dir, "coefficients");
        let file = File::create(filepath).unwrap();
        let mut writer = BufWriter::new(file);
        for iter in &coefficients {
            writeln!(writer, "iter {}", iter.iter).unwrap();
            writeln!(writer, "Full coefficients:").unwrap();
            for (i, z) in iter.c_full.iter().enumerate() {
                writeln!(writer, "{:4} {:.8e}", i, z).unwrap();
            }
            writeln!(writer, "Relevant space coefficients:").unwrap();
            for (i, z) in iter.c_relevant.iter().enumerate() {
                writeln!(writer, "{:4} {:.8e}", i, z).unwrap();
            }
            writeln!(writer, "Null space coefficients:").unwrap();
            for (i, z) in iter.c_null.iter().enumerate() {
                writeln!(writer, "{:4} {:.8e}", i, z).unwrap();
            }
            writeln!(writer).unwrap(); 
        }
    }

    let d_total = t_total.elapsed();

    (e, d_total, d_basis, d_hs, d_prop)
}

/// Perform stochastic propagation in the NOCI-QMC space. 
/// # Arguments:
///     `ao`: AoData, contains AO integrals and other system data.
///     `input`: Input, user input specifications.
///     `states`: [SCFState], converged SCF states. 
///     `noci_reference_basis`: [SCFState], the converged SCF states filtered for those requested
///                             to be in the NOCI basis.
///     `c0`: [f64], initial coefficient vector of basis states.
///     `world`: Communicator, MPI communicator object (MPI_COMM_WORLD).
pub fn run_qmc_stochastic_noci(ao: &AoData, input: &mut Input, noci_reference_basis: &[SCFState], c0: &[f64], world: &impl Communicator, tol: f64, 
                               wicks: Option<&WicksView>) -> (f64, Duration, Duration, Duration, StochStepTimings) {

    let t_total = Instant::now();
    let irank = world.rank();

    if irank == 0 {
        println!("{}", "=".repeat(100));
        println!("Building NOCI-QMC basis....");
    }
    
    // Build excitations atop NOCI-reference basis.
    let t_basis = Instant::now();
    let basis = generate_qmc_noci_basis(noci_reference_basis, input);
    let d_basis = t_basis.elapsed();
    let n = basis.len();

    // Save indices in the coefficients vector of the references.
    let ref_indices: Vec<usize> = noci_reference_basis.iter().map(|ref_st| {basis.iter()
                                  .position(|qmc_st| qmc_st.label == ref_st.label).unwrap()}).collect();

    // Embed reference NOCI coefficient vector in full NOCI-QMC space.
    let mut c0qmc = vec![0.0_f64; n]; 
    for (i, ref_st) in noci_reference_basis.iter().enumerate() {
            let idx = basis.iter().position(|qmc_st| qmc_st.label == ref_st.label).unwrap();
            c0qmc[idx] = c0[i];
    }

    if irank == 0 {
        println!("Built NOCI-QMC basis of {} determinants.", n);
        println!("Running stochastic NOCI-QMC propagation....");
    }

    // Choose initial shift.
    let mut es = basis[0].e;

    // Perform the propagation.
    let t_prop = Instant::now();
    let (e, local_hist, step_timings) = step(&c0qmc, ao, &basis, &mut es, input, &ref_indices, world, tol, noci_reference_basis, wicks);
    let d_prop = t_prop.elapsed();

    // Write excitation histogram to a file. This should currently only be used if doing a single 
    // geometry at a time otherwise the previous file will be overwritten. Writes one file per rank.
    if let Some(hist) = local_hist.as_ref() && input.write.write_excitation_hist {
        if irank == 0 {println!("Writing excitation samples to file...");}
        let filepath = format!("{}/excitationsamples{}", input.write.write_dir, irank);
        let file = File::create(filepath).unwrap();
        let mut writer = BufWriter::new(file);

        writeln!(writer, "{} {} {}", hist.logmin, hist.logmax, hist.nbins).unwrap();
        writeln!(writer, "{} {} {}", hist.ntotal, hist.noverflow_low, hist.noverflow_high).unwrap();

        for &c in &hist.counts {
            writeln!(writer, "{}", c).unwrap();
        }
    }

    let d_total = t_total.elapsed();

    (e, d_total, d_basis, d_prop, step_timings)
}

/// Print important information for current geometry.
/// # Arguments:
///     `res`: Results, contains the aforementioned important information.
///     `input`: Input, user input specifications.
fn print_report(res: &Results, input: &Input) {
    println!("{}", "=".repeat(100));

    println!("Total PySCF time: {:?}", res.timings.pyscf);
    println!("Total SCF time: {:?}", res.timings.scf);

    println!("Total Reference NOCI time: {:?}", res.timings.noci_ref_total);
    println!(r" S & H_1 & H_2: {:?}", res.timings.noci_ref_hs);

    println!("Wick's Intermediates Construction time: {:?}", res.timings.wicks_intermediates);

    if input.det.is_some() {
        println!("Total NOCI-QMC deterministic time: {:?}", res.timings.qmc_det_total);
        println!(r"  Basis generation:  {:?}", res.timings.qmc_det_basis);
        println!(r"  S & H_1 & H_2: {:?}", res.timings.qmc_det_hs);
        println!(r"  Deterministic propagation:  {:?}", res.timings.qmc_det_prop);
    }

    if input.qmc.is_some() {
        println!("Total NOCI-QMC stochastic time: {:?}", res.timings.qmc_stoch_total);
        println!(r"  Basis generation:  {:?}", res.timings.qmc_stoch_basis);
        println!(r"  Stochastic propagation:  {:?}", res.timings.qmc_stoch_prop);
        println!(r"     Walker initialisation: {:?}", res.timings.qmc_stoch_step.initialse_walkers);
        println!(r"     Spawning, Death and Cloning: {:?}", res.timings.qmc_stoch_step.spawn_death_collect);
        println!(r"     Accumulate updates and pack MPI buffers: {:?}", res.timings.qmc_stoch_step.acc_pack);
        println!(r"     Exchange spawn updates MPI: {:?}", res.timings.qmc_stoch_step.mpi_exchange_updates);
        println!(r"     Unpack updates and accumulate: {:?}", res.timings.qmc_stoch_step.unpack_acc_recieved);
        println!(r"     Apply population updates: {:?}", res.timings.qmc_stoch_step.apply_delta);
        println!(r"     Update pG: {:?}", res.timings.qmc_stoch_step.update_p);
        println!(r"     Calculate ||C||, ||SC||: {:?}", res.timings.qmc_stoch_step.calc_populations);
        println!(r"     Calculate projected energy  : {:?}", res.timings.qmc_stoch_step.eproj);
    }

    println!("{}", "=".repeat(100));
    println!("R: {}", res.r);
    for (i, st) in res.states.iter().enumerate() {
        println!("State({}): {},  E: {}", i + 1, st.label, st.e);
    }

    println!("State(NOCI-reference): E: {}, [E - E(RHF)]: {}", res.e_noci_ref, res.e_noci_ref - res.e_rhf);
    if let Some(e_det) = res.e_noci_qmc_det {println!("State(NOCI-qmc-deterministic): E: {}, [E - E(RHF)]: {}", e_det, e_det - res.e_rhf);}
    if res.e_noci_qmc_stoch.is_some() {println!("State(NOCI-qmc-qmc): Blocking analysis must be performed");}
    if let Some(e_fci) = res.e_fci {println!("State(FCI): E: {},  [E - E(RHF)]: {}", e_fci, e_fci - res.e_rhf);}

    println!("{}", "=".repeat(100));
}
