// read.rs
// External crate imports.
use hdf5::File;
use hdf5::types::VarLenUnicode;
use ndarray::{Array1, Array2, Array4};

// Crate-root imports.
use crate::maths::loewdin_x;
use crate::{AoData, Result};

/// Antisymmetrise the ERIs as:
///     `t[a, b, c, d] = (ab|cd) --> (ab||cd) = (ab|cd) - (ac|bd)`.
/// # Arguments
/// - `eri_coul`: Coulomb ERIs.
/// # Returns
/// - `Array4<f64>`: Antisymmetrised ERIs.
fn antisymmetrise(eri_coul: &Array4<f64>) -> Array4<f64> {
    let eri_exch = eri_coul.view().permuted_axes([0, 2, 1, 3]).to_owned();
    eri_coul - &eri_exch
}

/// Read in AO integrals (h, eri, s, dm) and other miscellaneous data (enuc, nao,  nelec, aolabels)
/// from HDF5 generated by PySCF.
/// # Arguments
/// - `path`: Path to data file.
/// # Returns
/// - `AoData`: AO integrals and associated metadata read from the HDF5 file.
pub fn read_integrals(path: impl AsRef<std::path::Path>) -> Result<AoData> {
    let f = File::open(path)?;

    let n: usize = f.dataset("nao")?.read_scalar()?;

    let eri_coul: Array4<f64> = f.dataset("eri")?.read()?;
    let eri_asym = antisymmetrise(&eri_coul);

    let s: Array2<f64> = f.dataset("S")?.read()?;
    let x = loewdin_x(&s, false, 1e-12);

    let h: Array2<f64> = f.dataset("h")?.read()?;
    let enuc: f64 = f.dataset("Enuc")?.read_scalar()?;
    let nelec: Array1<i64> = f.dataset("nelec")?.read()?;
    let dm: Array2<f64> = f.dataset("dm")?.read()?;

    let ds = f.dataset("aolabels")?;
    let arr = ds.read_1d::<VarLenUnicode>()?;
    let labels: Vec<String> = arr.iter().map(|v| v.to_string()).collect();

    let e_fci: Option<f64> = if f.link_exists("E_fci") {
        Some(f.dataset("E_fci")?.read_scalar::<f64>()?)
    } else {
        None
    };

    Ok(AoData {
        s,
        x,
        h,
        eri_coul,
        eri_asym,
        enuc,
        n,
        nelec,
        dm,
        labels,
        e_fci,
    })
}
